### PR TITLE
Refactor/errors

### PR DESCRIPTION
**Pull request by live627**
Pushing this lest I forget again.

### CODE REVIEW

**Comment by emanuele45** [comment]
Is this ready to merge? (Just to be sure.)

**Comment by live627** [comment]
yes

**Comment by emanuele45** [comment]
Ouch... i didn't even check the code... well, if something breaks it's your fault @live627 !! :smiling_imp:

**Comment by live627** [comment]
* evil grin

I should have put in a backdoor!

**Pull request merged**
