### PR TITLE
FIX GroupBy SQL error risen by PostGresql

### PR DESCRIPTION
**Pull request by cbrouillard**

### CODE REVIEW

**Comment by Spuds** [comment]
Thanks for the PR ... Where you getting a ```column must appear in the GROUP BY clause or be used in an aggregate function``` error ?  Also which version of Postgres and ElkArte are you running?

**Comment by cbrouillard** [comment]
Hi !
Yes it was this error : column must appear in the GROUP BY clause or be
used in an aggregate function
and it occurred when I tried to move a topic.

Elkarte version is : 1.1.6
PostgreSQL version is : 9.6

Have a great day

BROUILLARD Cyril
---------------------------------------------
cyril.brouillard@gmail.com

**Comment by live627** [comment]
````
 Showing rows 0 -  2 (3 total, Query took 0.0005 seconds.)

SELECT id_board, approved, COUNT(*) AS num_topics, SUM(unapproved_posts) AS unapproved_posts,
	SUM(num_replies) AS num_replies
FROM smf_topics
WHERE id_topic IN (1,58,176,2,21,50,3)
GROUP BY id_board, approved

id_board	approved	num_topics	unapproved_posts	num_replies	
1	1	3	0	149627	
31	1	1	0	47	
55	1	3	0	131	


Your SQL query has been executed successfully.

EXPLAIN SELECT id_board, approved, COUNT(*) AS num_topics, SUM(unapproved_posts) AS unapproved_posts,
			SUM(num_replies) AS num_replies
		FROM smf_topics
		WHERE id_topic IN (1,58,176,2,21,50,3)
		GROUP BY  id_board, approved



1	SIMPLE	smf_topics	range	PRIMARY	PRIMARY	3	
    NULL
	7	Using where; Using temporary; Using filesort	


 Showing rows 0 -  6 (7 total, Query took 0.0005 seconds.)

SELECT id_board, approved, COUNT(*) AS num_topics, SUM(unapproved_posts) AS unapproved_posts,
	SUM(num_replies) AS num_replies
FROM smf_topics
WHERE id_topic IN (1,58,176,2,21,50,3)
GROUP BY id_topic, id_board, approved


id_board	approved	num_topics	unapproved_posts	num_replies	
1	1	1	0	149551	
55	1	1	0	47	
31	1	1	0	47	
55	1	1	0	41	
55	1	1	0	43	
1	1	1	0	36	
1	1	1	0	40	


Your SQL query has been executed successfully.

EXPLAIN SELECT id_board, approved, COUNT(*) AS num_topics, SUM(unapproved_posts) AS unapproved_posts,
			SUM(num_replies) AS num_replies
		FROM smf_topics
		WHERE id_topic IN (1,58,176,2,21,50,3)
		GROUP BY id_topic, id_board, approved



1	SIMPLE	smf_topics	range	PRIMARY	PRIMARY	3	
    NULL
	7	Using where; Using temporary; Using filesort	
```

**Comment by emanuele45** [comment]
@live627 in your second query you have added id_topic to group by, but not to the select (where is needed to later populate `$fromCacheBoards`).

TBH I'm a little confused by `num_topics` in this query... if I'm not misinterpreting something, it should always be 1 (having id_topic in the group by it would mean 1 topic moved from one board to the other).

**Comment by live627** [comment]
This  is just a demonstration of how this PR affected  the results of this query.

A test case should be made to ensure that these changes don't break the highly confusing  code.

---
This query is also present in SMF, which is why I'm interested in this. All three aggregates report the totals for the entire board A monkey wrench has been introduced in elk where the topic  id is fetched for some reason. This is why it is paramount that each new change must come with a unit test.

**Comment by emanuele45** [comment]
Yes, I understand, in that case, the result does not change anything (unless I'm blind and that can happen), because from your first query you get:
```
id_board	approved	num_topics	unapproved_posts	num_replies	
1	1	3	0	149627	
31	1	1	0	47	
55	1	3	0	131	
```

and the values of $fromBoards while looping over the results would be:
```
1st loop:

$fromBoards[
	1 => [
		'num_posts' => 149627 + 3,
		'num_topics' => 3,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 1
	]
]

2nd loop:
$fromBoards[
	1 => [
		'num_posts' => 149627 + 3,
		'num_topics' => 3,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 1
	],
	31 => [
		'num_posts' => 47 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 1
	]
]

3rd loop:
$fromBoards[
	1 => [
		'num_posts' => 149627 + 3,
		'num_topics' => 3,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 1
	],
	31 => [
		'num_posts' => 47 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 31
	],
	55 => [
		'num_posts' => 131 + 3,
		'num_topics' => 3,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 55
	]
]
```

In the "new version", you reported these results:
```
id_board	approved	num_topics	unapproved_posts	num_replies	
1	1	1	0	149551	
55	1	1	0	47	
31	1	1	0	47	
55	1	1	0	41	
55	1	1	0	43	
1	1	1	0	36	
1	1	1	0	40	
```
though, as I said, you are missing the value of id_topic, it's not very important, anyway I guess it would look something like this:
```
id_topic	id_board	approved	num_topics	unapproved_posts	num_replies	
1	1	1	1	0	149551	
58	55	1	1	0	47	
176	31	1	1	0	47	
2	55	1	1	0	41	
21	55	1	1	0	43	
50	1	1	1	0	36	
3	1	1	1	0	40	
```

So, looping over these results we will get:
```
1st loop:

$fromBoards[
	1 => [
		'num_posts' => 149551 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 1
	]
]

2nd loop:

$fromBoards[
	1 => [
		'num_posts' => 149551 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 1
	],
	55 => [
		'num_posts' => 47 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 55
	]
]

3rd loop:

$fromBoards[
	1 => [
		'num_posts' => 149551 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 1
	],
	55 => [
		'num_posts' => 47 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 55
	],
	31 => [
		'num_posts' => 47 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 31
	]
]

4th loop:

$fromBoards[
	1 => [
		'num_posts' => 149551 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 1
	],
	55 => [
		'num_posts' => 47 + 1 + 41 + 1,
		'num_topics' => 1 + 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 55
	],
	31 => [
		'num_posts' => 47 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 31
	]
]

5th loop:

$fromBoards[
	1 => [
		'num_posts' => 149551 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 1
	],
	55 => [
		'num_posts' => 47 + 1 + 41 + 1 + 43 + 1,
		'num_topics' => 1 + 1 + 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 55
	],
	31 => [
		'num_posts' => 47 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 31
	]
]

6th loop:

$fromBoards[
	1 => [
		'num_posts' => 149551 + 1 + 36 + 1,
		'num_topics' => 1 + 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 1
	],
	55 => [
		'num_posts' => 47 + 1 + 41 + 1 + 43 + 1,
		'num_topics' => 1 + 1 + 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 55
	],
	31 => [
		'num_posts' => 47 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 31
	]
]

7th loop:

$fromBoards[
	1 => [
		'num_posts' => 149551 + 1 + 36 + 1 + 40 + 1,
		'num_topics' => 1 + 1 + 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 1
	],
	55 => [
		'num_posts' => 47 + 1 + 41 + 1 + 43 + 1,
		'num_topics' => 1 + 1 + 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 55
	],
	31 => [
		'num_posts' => 47 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 31
	]
]
```
That summing up leads to:
```
$fromBoards[
	1 => [
		'num_posts' => 149627 + 3,
		'num_topics' => 3,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 1
	],
	55 => [
		'num_posts' => 131 + 3,
		'num_topics' => 3,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 55
	],
	31 => [
		'num_posts' => 47 + 1,
		'num_topics' => 1,
		'unapproved_posts' => 0,
		'unapproved_topics' => 0,
		'id_board' => 31
	]
]
```
That is exactly the same values as the one from the "old" query.

So, nothing has changed unless I'm blind.

**Comment by emanuele45** [comment]
@Spuds I thought this one was already merged... :man_facepalming: 
Do you see any issue?

**Pull request merged**
