### PR TITLE
Some more or less random things as we clean up for an RC

### PR DESCRIPTION
**Pull request by Spuds**
@live627 I had to make a couple of minor adjustments due to changes with the new settings class.  

One was the birthday email previews were not displaying as var_message was removed from the template, I changed that back https://github.com/elkarte/Elkarte/pull/2751/commits/c4cb2b6daea764ac59321113b5f251356e80a9db

Second was the cache description was not displaying, for that I had to use 'desc' twice in the config vars array https://github.com/elkarte/Elkarte/pull/2751/commits/e31e031d0657897c71bb127156e9d653ab29aae3 Not sure those are the correct things so would appreciate if you could take a look and see if something else should be done instead of what I did.

### CODE REVIEW

**Comment by emanuele45** [comment]
@Spuds would you mind grabbing the fix at #2741 ? :angel:

**Comment by Spuds** [comment]
Got it, will update the PR soon

**Comment by Spuds** [comment]
Nuff for now I think

**Comment by Spuds** [comment]
And now I'll fix the conflicts, happy days

**Pull request merged**
