### PR TITLE
Removed initial default argument on insert

### PR DESCRIPTION
**Pull request by tinoest**
It doesn't have any impact or effect when '' is used, as that evaluates to INSERT on the line starting $queryTitle

### CODE REVIEW

**Comment by tinoest** [comment]
This probably needs further testing, but I couldn't see any impact. I'm unsure why it was written like that historically.

**Comment by Spuds** [comment]
@emanuele45 do you recall why it was like that?  Its the cause of some error log entries (server not elkarte)

**Comment by tinoest** [comment]
```
PHP Deprecated:  Required parameter $table follows optional parameter $method in /var/www/html/elkarte/sources/database/Db-mysql.class.php on line 711
PHP Deprecated:  Required parameter $columns follows optional parameter $method in /var/www/html/elkarte/sources/database/Db-mysql.class.php on line 711
PHP Deprecated:  Required parameter $data follows optional parameter $method in /var/www/html/elkarte/sources/database/Db-mysql.class.php on line 711
PHP Deprecated:  Required parameter $keys follows optional parameter $method in /var/www/html/elkarte/sources/database/Db-mysql.class.php on line 711
```

Those are the error's if it helps at all.

**Comment by Spuds** [comment]
And I think that will actually fail on php8, its a lot more strict about parameters

**Comment by tinoest** [comment]
> And I think that will actually fail on php8, its a lot more strict about parameters

It's actually raised on php8.0 

https://php.watch/versions/8.0/deprecate-required-param-after-optional

I hadn't noticed my development box was running PHP 8.0, when testing. I thought I had reverted back to PHP 7.4

**Comment by emanuele45** [comment]
Spuds wrote on 2/17/21 9:00 PM:
>
> @emanuele45 <https://github.com/emanuele45> do you recall why it was 
> like that? Its the cause of some error log entries (server not elkarte)
>

TBH I never understood why it was done that way. The method is always 
specified, so no matter what that default is overridden. *shrugs*

IIRC in 2.0 is already gone last time I played with the db stuff.

**Comment by emanuele45** [comment]
Martyn Brown wrote on 2/17/21 6:52 PM:
>
> This probably needs further testing, but I couldn't see any impact. 
> I'm unsure why it was written like that historically.
>

AFAICT it was done like this on first commit without explanations (by 
Grudge).
I guess it was to indicate a sort of default, but since the argument has 
to always be specified it has always been pretty useless, but remained 
just because PHP didn't complain.

**Pull request merged**
