### PR TITLE
Fix 1.1 upgrade - fixes #2264

### LINKED ISSUE #2264: Syntax Error upgrade_1-1.php
Last pull request #2260 from Spuds/Misc_Fix

Error notice by upgrade:

Parse error: syntax error, unexpected 'array' (T_ARRAY) in C:\xampp\htdocs\elk11test\install\upgrade_1-1.php on line 378

### PR DESCRIPTION
**Pull request by emanuele45**

### CODE REVIEW

**Comment by wintstar** [comment]
Not work.The next error:
Fatal error: Call to undefined method UpgradeInstructions_upgrade_1_1::db_list_columns() in C:\xampp\htdocs\elk11test\install\upgrade_1-1.php on line 443

**Comment by emanuele45** [comment]
Added some more...
Does that mean I should really test the code I write?... too tired to do so, sorry. :crying_cat_face:

**Comment by wintstar** [comment]
I will test it tomorrow. At first glance this seems to work =>  Fix another issue with upgrade_1-1 - thanks winstar for reporting

**Comment by emanuele45** [comment]
Please do **NOT** merge the branch, the testing is probably broken, I have to fix it first. ;)

**Comment by Spuds** [comment]
So your saying you want me to merge this right now ?? :tongue:

**Comment by emanuele45** [comment]
At least it would be a known bug! :lollipop:

**Comment by emanuele45** [comment]
Now is fixed.
I think I'm testing also the selenium directory, but better something more than not enough. :P

**Pull request merged**
