### PR TITLE
Minor code cleanup, added fastcgi exit for scheduled tasks.

### PR DESCRIPTION
**Pull request by Vekseid**
Also removed a duplicate CACHE_STALE define, and moved start time before the defines (they're slow).

### CODE REVIEW

**Comment by Spuds** [comment]
Thank you :+1: 

Note I'm not seeing the duplicate CACHE_STALE define other than in SSI which I don't think is avoidable, well it probably is if we move defines somewhere common.  Drat, that was a 1.02 check on my part, need to check on 1.1 as well.

**Comment by emanuele45** [comment]
https://github.com/Vekseid/Elkarte/blob/d6b4aa9345178e8cf219218c569b86dcf907324e/index.php#L29
https://github.com/Vekseid/Elkarte/blob/d6b4aa9345178e8cf219218c569b86dcf907324e/index.php#L48

I probably did some mistake while moving stuff around... :angel:

**Comment by Vekseid** [comment]
> other than in SSI which I don't think is avoidable, well it probably is if we move defines somewhere common.

It looks like this is what bootstrap.php should be for, for SSI, index, and install, but isn't >_>

**Comment by Spuds** [comment]
Yup, my mistake, checked the wrong branch :tomato:

**Comment by emanuele45** [comment]
> It looks like this is what bootstrap.php should be for, for SSI, index, and install, but isn't >_>

Yep, bootstrap.php is indeed not finished at all, I just extracted the basics and added the file in order to have "something" to work on and use it on the few files that are run as cron jobs or alike.
Use it in index.php should be the way to go.

**Pull request merged**
