### PR TITLE
Fix session handler, as Db::insert returns nothing.

### PR DESCRIPTION
**Pull request by kode54**
Maybe the Database classes should be changed instead? That's a big assumption to expect code to not check a return value from insert(), since it may be expected to return success or failure.

### CODE REVIEW

**Comment by emanuele45** [comment]
Something seems broken...

**Comment by kode54** [comment]
This is what I get for making a PR against a patch branch instead of master.

**Comment by kode54** [comment]
Bumping to post a comment about why checking the row count for the update query is a bad idea. At least with the version of MariaDB I have installed, if you update a row with the same values it currently contains, it will return 0 rows affected. Sure, this shouldn't happen if the timestamp is different, but what if multiple session writes occur in the same second?

**Comment by kode54** [comment]
Checking for dupes now, rolling another update.

**Comment by emanuele45** [comment]
> This is what I get for making a PR against a patch branch instead of master.

Well, that's the correct thing to do. :wink: 

Let's try to get the conditions the error occur: what version of php do you have? What version of mariadb?

**Comment by kode54** [comment]
PHP 7.0.8
MariaDB 5.5.47

The error occurs if someone triggers the session save multiple times in one second. The logged errors all occur grouped into one timestamp, 2-4 errors per instance.

**Comment by emanuele45** [comment]
So the issue is that when a session is stored with the same timestamp and the same data...
Could you try adding in Session.php after the line:
```
$sc = $_SESSION['session_value'];
```
this:
```
$_SESSION['mictrotime'] = microtime();
```

it's mainly a workaround, but it should change the data and force the db to return a affected_rows in all the cases (unless of very unfortunate events).

... unless I'm wrong, of course! lol

**Comment by kode54** [comment]
That seems to work. I'll let you know if any further session issues arise.

**Comment by emanuele45** [comment]
I submitted the workaround discussed above in the 1.0.8.1 path.
I'm closing this one so that we don't have PR hanging, probably we'd need a better fix, in that case, feel free to open a new issue referencing this PR for the discussion. ;D

**Comment by albertlast** [comment]
About this mysql issue (is not a php7 issue in my eyes),
i fixed in this way: https://github.com/SimpleMachines/SMF2.1/pull/3545

**Comment by emanuele45** [comment]
This morning I did a search and I remember there is just one situation that may be problematic in respect to this change... but I forgot to take not and I forgot which one it is... :sob:

**Pull request closed without merging**
