### PR TITLE
Some small fixes. Closes #2459

### LINKED ISSUE #2459: smallint -> mediumint for pm count in members table.
Two of Elliquiy's members hit the smallint threshold awhile back, so I had to update the table.

It's a small thing, but still.

### PR DESCRIPTION
**Pull request by Vekseid**
Just a few basic fixes I did while trying to setup proper e-mail testing.

### CODE REVIEW

**Comment by Vekseid** [comment]
Something up with Travis?

**Comment by Spuds** [comment]
Ah the joys of 5.3 ... no session_status()

**Comment by Vekseid** [comment]
What's up with php 7 going missing on the MySQL branch though?

**Comment by Spuds** [comment]
Just Travis being a naughty boy ... I'll restart that run

**Comment by emanuele45** [comment]
If someone has reached this limit I start wondering if smallint is too low for mentions...

**Comment by Vekseid** [comment]
People generally won't be keeping mentions around.

People do keep their roleplays, though.

**Pull request merged**
