### PR TITLE
Fix for Issue #3120

### PR DESCRIPTION
**Pull request by ahrasis**

### CODE REVIEW

**Comment by emanuele45** [comment]
Is this an issue with 1.1.2 or with the development version? (I'm not sure when this was changed.)

**Comment by emanuele45** [comment]
Okay I saw the issue and the link to the topic, so it is 1.1.2.
Do note: I'll create a branch for 1.1.3 later today. The patch will go there so this PR will not be merged in development. ;)

**Comment by emanuele45** [comment]
Added to 7be8ed961e1b6dd1d018b0fd1f8f5a3067f478c1

**Comment by ahrasis** [comment]
This was not included in 1.1.3 in both patch and install packages.

**Pull request closed without merging**
