### PR TITLE
git repos attempt to store the file cache for themes, fix?

### PR DESCRIPTION
**Pull request by FictionCircle**

### CODE REVIEW

**Comment by FictionCircle** [comment]
Up to you, I can just fix it whenever I mess with it.

**Comment by emanuele45** [comment]
It's right to add the exception, just could you use... dunno:
```
hive*
```
just to allow the index.php talready there?

**Comment by cody3647** [comment]
The main cache directory isn't ignored either

**Comment by FictionCircle** [comment]
Yeah I realized I forgot to copy that over. Oops. Should be fixed for both now.

**Comment by emanuele45** [comment]
The main cache directory is ignored:
https://github.com/elkarte/Elkarte/blob/development/.gitignore#L4

**Comment by cody3647** [comment]
Hmm.  Must have gotten confused there.

**Comment by FictionCircle** [comment]
> cache/data*.php

https://github.com/elkarte/Elkarte/blob/8214f42dc6c370bfe60018b2517776b7b982798e/sources/subs/CacheMethod/Filebased.php#L46

https://github.com/elkarte/Elkarte/commit/85baa540d059416f0dedaf8a916b57d1c2af1296

> cache/data*.json

They were switched to .json files so its no longer ignored.

**Comment by emanuele45** [comment]
Actually, I didn't notice the json switch. :-\
It's not really a good thing TBH.
The cache file area/were PHP as an additional line of defence against leaking of sensitive data (yes, the file names are random, and all, but misconfiguration may expose the directory listing and json files are plain text files that can be read from the net.

I'll do a quick restore for RC1, it may generate broken php files, but it doesn't really matter that much.

**Comment by FictionCircle** [comment]
@emanuele45 

Yeah, I thought it was odd but I have .json setup to execute as .php so I wasn't worried about it. You could just leave it alone and just change the extension to .php instead of a restore (which I'm assuming means revert).

**Comment by emanuele45** [comment]
Change the extension alone wouldn't make much difference, without a php opening tag. ;)
I'm adding to #2842

**Pull request merged**
