### PR TITLE
Some general style and issue cleanup

### PR DESCRIPTION
**Pull request by Vekseid**
My IDE is still going nuts, so I figured I would address the css stuff in small chunks.

Also, setup a symlinked deployment environment. Turns out this does not work well with __DIR__

### CODE REVIEW

**Comment by emanuele45** [comment]
Yep, known limitation that DIR doesn't cope with symlinks, but Elk actually relies on it some way or another (see the one instance you didn't remove).
My dev environment is pretty similar to the one you use, but I have symlinked only sources and themes, index.php and the few files in the root are "real" files...

**Comment by Vekseid** [comment]
Well, to fix that we could just move that logic over to Settings.php

But really I just wanted to be able to run it the way I had it.

**Comment by emanuele45** [comment]
I just stripped them all from Settings.php not a long time ago based on the assumption that a settings file should just hold settings and not logic. lol

**Comment by Vekseid** [comment]
Grabbing the proper install directory is a setting in my book.

Not that it matters too much, YMMV.

**Comment by emanuele45** [comment]
Sorry, I've been a bit busy on other things.

> Grabbing the proper install directory is a setting in my book.

I tried to remove any login from Settings.php, because it seemed to me cleaner. In an ideal world I think the settings file could even be a yaml file for example.
Try to guess if there is around an install directory is not really a setting, more a wild guess to be sure nothing bad could happen.

But you are right YMMV. ;)

Well, I'll merge this waiting to find out what to do with ```__FILE__``` and ```__DIR__```.

**Pull request merged**
