### PR TITLE
Removal of another few globals and cleanup

### PR DESCRIPTION
**Pull request by emanuele45**

### CODE REVIEW

**Comment by Spuds** [comment]
498 files changed 🥇 Awesome cleanup.

**Comment by emanuele45** [comment]
Well... mostly was the changes in the headers! :laughing: 
Okay, now I think I'll have another look at the attachments code, I realized there is something that smells there... :-\

**Comment by Spuds** [comment]
I think a lot of whats going on is the new name spacing ... the ::hooks functions in the various modules need to be fully qualified.  Also at least for attachments it calls off Attachments_Post_Module which is now just Post.   At least I think that is the base of the issue of why it (and drafts etc) are not loading.

**Comment by emanuele45** [comment]
hmm... they should be already fully qualified, maybe I changed the names and didn't update them in upgrade or install... that could very well be the reason.
Up to 1.1 the name of the class was something like Attachments_Post_Module, while in dev is Post.

**Comment by Spuds** [comment]
That takes care of it... FYI I had changed the code in the getModuleClass to be
```
		$module_class = explode('\\', trim(get_class($this), '\\'));
		$module_class= end($module_class);
```
I thought that was more generic, but the str_replace is fine as well.  You may need to rebase to avoid the conflict.

**Comment by emanuele45** [comment]
It does make sense. Since it's looking for the controller name it should work much better! :+1:

**Comment by emanuele45** [comment]
BTW I didn't apply the patch, just generated it, so feel free to apply it, I'll take it in when is merged. ;D

**Comment by Spuds** [comment]
Will do .. I have it as part of my graphic.subs change over to a class branch.  I'm getting there, but  it will need more work as unraveling the madness was a bit messy 💃

**Comment by emanuele45** [comment]
LOL
I've worked a bit on the attachments directories now to streamline madness there.
And I'll start checking also attachments themselves to see if I can get something more... manageable.hash('sha1', hash('md5', $filename . time()) . mt_rand())

**Comment by Spuds** [comment]
We are only going with auto years on the automanage directory thing correct ??  At least I recall a discussion along those lines.  Removing all those options should be a help.

Maybe a good use for the TokenHash class that we have, it should be able to generate any hash length that we need.

**Comment by emanuele45** [comment]
There is #3193 about it, yes.
For the moment, though, I'm trying to actually find the logic behind all the juggling that an attachment does. :rofl:
This is where I am right now:
https://github.com/elkarte/Elkarte/compare/development...emanuele45:attachments_rework?expand=1

**Pull request merged**
