### PR TITLE
Auto bounce detection - Preliminary

### PR DESCRIPTION
**Pull request by Targren**
Post-By-Email address detects DSN (bounces), records in failed PBE table with a new, bounce-specific failure case. (Previous req Closed to fix a stupid bug)

### CODE REVIEW

**Comment by Vekseid** [comment]
To clarify my last post, the following happens a lot more often than you may think

1. User requests password reset.
2. Reset mail bounces, because the account's been disabled/deleted.
3. User logs in and reactivates their account.
4. User (usually) realizes this, and requests a password reset mail again.

There may be value in setting a separate flag, and blocking the mail if too many reset requests are made in a short time, but there may be a better way to handle that.

**Comment by emanuele45** [comment]
Cool stuff! (I've been a bit busy before.)

>  do you want a "dirty" flag to prevent just notification emails from going out, or "control" emails (e.g. password resets, etc..) as well? I'd personally lean towards the former, just to prevent a full lockout that needs admin intervention, but, on the other hand, the situation would really be barely different from forgetting the password and having lost access to the email account situation we've already got.

Good question.
I guess there is no reason to send out emails that we already know are not going to reach the destination, on the other hand, it could be the bounce is caused by a temporary problem, so I guess "control" emails could be send anyway.

There are a couple of tweaks to do on the coding style, but it's not really a problem, we can uniform it when integrated. ;D

Let me know if you want to refine the code before merging or if it is better to have it merged.

**Comment by Targren** [comment]
This part of the code is pretty straightforward and nailed down, so I think it'd be better to have it merged, at least so we can get some more eyes on it and some more mail servers shooting at it - still have to be ready for all those exceptions. 

Sorry about the coding style faux pas. I'm trying to keep it in mind, but sometimes switching between the work style and ElkArte's isn't as seamless as I'd like. :)

**Comment by emanuele45** [comment]
No problem, fix style is easy enough. ;)
I could even do it without introducing new bugs in the meantime. :laughing:

**Pull request merged**
