### PR TITLE
Correctly autoload addon integration files

### PR DESCRIPTION
**Pull request by live627**
http://www.elkarte.net/community/index.php?topic=4204.msg30163#msg30163

@emanuele45 has been slacking 😛 

(talking to oneself in the third person is a sign of the utmost confidence)

### CODE REVIEW

**Comment by emanuele45** [comment]
Restarted the build.

**Comment by emanuele45** [comment]
@Spuds any idea why this is the only branch failing?
I already restarted once, may it just needs a second nudge?

**Comment by emanuele45** [comment]
Could it be https://travis-ci.org/elkarte/Elkarte/jobs/215370631#L373 ?

**Comment by live627** [comment]
Jep.

**Pull request merged**
