### PR TITLE
Moar fixes

### PR DESCRIPTION
**Pull request by emanuele45**
Another round of fixes for 1.1

### CODE REVIEW

**Comment by meetdilip** [comment]
Nice update

**Comment by emanuele45** [comment]
@Spuds give a second (and maybe a third) look at the last commit (considering I had typos in the commit message as well it's better to be extra safe LOL), I removed some stuff from BeSocial to align it to Light (I also uploaded the file to elk.net for testing) and I hope I didn't break anything. :angel:

**Comment by Spuds** [comment]
Looks correct to me ... beSocial needs a bit of help anyway to catch it up to the framework changes. , I'll make another pass on it this weekend ... most of what it needs now is border:none or border: 1px solid transparent in various spots to bring it back to its old self (and I need to the the SVG's for the board icons for that theme) .. anyway it will take a couple of passes!

**Comment by emanuele45** [comment]
> Looks correct to me ...
>

Cool! :D

> beSocial needs a bit of help anyway to catch it up to the framework
> changes. , I'll make another pass on it this weekend ... most of what
> it needs now is border:none or border: 1px solid transparent in
> various spots to bring it back to its old self (and I need to the the
> SVG's for the board icons for that theme) .. anyway it will take a
> couple of passes!
>

Great! :D
I don't see that many differences, but I just had a quick look around,
so I certainly missed many.

**Pull request merged**
