### PR TITLE
The followup parameter can come from both a GET or a POST, so... getRequest - fixes #3497

### LINKED ISSUE #3497: Followups Not Working
**Describe the bug**
Use "more" dropdown and select "quote to new topic".

You are redirected to a new topic post page as expected but w/o the quoted message.  Go through the posting process and its not a followup as it should be.

**ElkArte info**
1. 2.0

### PR DESCRIPTION
**Pull request by emanuele45**
That was kind of easy. :D

### CODE REVIEW

**Comment by Spuds** [comment]
Looks like one of many issues caused by my $req implementation.  Thanks for the find!

**Comment by emanuele45** [comment]
@Spuds should I care about the maxpain tests failing?

**Comment by Spuds** [comment]
I had pushed a fix (yesterday) that fixed the tests (or at least should have).  There were a few issues, one was pointing to the elksite which should have been easy to remedy, but it reveled a couple of other issues with our stream and fopen handlers that I fixed.

**Comment by emanuele45** [comment]
Rebased and pushed.

**Comment by Spuds** [comment]
Yeah, I fixed this again in another PR.  Its working but the search results, for some reason, changed a bit.  I think it was some odd regional result that I've tried to stabilize in the fix (set language etc).  Anyway going to merge this as the test error here will get sorted on its own.

**Pull request merged**
