### PR TITLE
Dropped "db_" prefix to many database-related methods and some more

### PR DESCRIPTION
**Pull request by emanuele45**
* added a fetch_all
* removed the "db_" thingy from method names
* removed some static variables
* simplified the "query" code moving out common stuff between mysql and postgre
* removed a begin/end transaction happening in query based on some kind of random guesses based on the assumption that if transaction is necessary it's up to the code writer to initiate and terminate it.

### CODE REVIEW

**Comment by Spuds** [comment]
Be nice to get rid of all those db_ 👍

**Comment by emanuele45** [comment]
So, after all this crap, I have no idea why it doesn't work. :joy: 
Apparently, for some inexplicable reason, the insert of the settings table during install for postrgesql doesn't insert anything. And from there everything else fails.
I have to dig more into it... :-\

**Comment by emanuele45** [comment]
And finally, after so many tries I even lost count, the tests are finally back working!!
 :dancing_men: :dancing_women: :dancer: :dancing_women: :dancing_men:

**Comment by emanuele45** [comment]
I think i don't want to touch this any further... and I hope I didn't left around any debug code... :sob:

**Comment by Spuds** [comment]
I'm going to merge it in so you avoid the temptation of adding to it !!! ... Really awesome work here 👍

**Pull request merged**
