### PR TITLE
Deprecations v2

### PR DESCRIPTION
**Pull request by emanuele45**
Another round of deprecated stuff removed.
Also added a method to the errors class to log an error message on the use of 2.0-deprecated functions, the idea is to remove these functions before RC and this can be helpful in testing addons (I hope).

### CODE REVIEW

**Comment by emanuele45** [comment]
BTW 852271f7b99b67fe0266b76bf4c77d639bd6b538 fixes #3077

**Comment by Spuds** [comment]
Is this ready to merge in?

**Comment by emanuele45** [comment]
I think so, yes.

**Comment by Spuds** [comment]
Good enough for me !

**Pull request merged**
