### PR TITLE
Query to fetch

### PR DESCRIPTION
**Pull request by emanuele45**
The original idea was to convert the "query" without identifier to "queryFetch", but I re-scoped to drop the unnecessary identifiers still hanging around.
There are still a few that I'm not sure how to get rid of, though... it's getting closer.

### CODE REVIEW

**Comment by emanuele45** [comment]
@Spuds looks like to fail on fetching elkarte.net?
Maybe firewall or such?

**Comment by Spuds** [comment]
We should update the test to https .... but I'd guess is that Travis uses its own DNS resolver and it did not respect the TTL I set on the old site in prep for the move.  If so it should self clear whenever Travis decides to refresh its resolver.   Or its just another test issue !

**Comment by Spuds** [comment]
@emanuele45 could you resolve the conflicts caused by the1.1.7  🐻 so we can get this merged in 👍

**Comment by emanuele45** [comment]
:crossed_fingers:

**Comment by Spuds** [comment]
Yeah!

**Pull request merged**
