### PR TITLE
Move most directory read functions to SPL

### PR DESCRIPTION
**Pull request by Spuds**
Move from scandir, opendir, glob, readdir bla bla etc to SPL objects.  Wrapped all in try/catch although the catch in most cases is a todo for maybe logging.

### CODE REVIEW

**Comment by emanuele45** [comment]
O_O

**Comment by Spuds** [comment]
Which part is confusing, or all of it, or just why :tongue:

**Comment by emanuele45** [comment]
LOL
Just "WOW". :stuck_out_tongue: 

BTW, travis fails here as well, not I feel a little bit less sick. :lollipop:

**Comment by Spuds** [comment]
Yeah, not sure what is going on with the travis 5.4/mysqli/selenium run ...and debugging travis is a PITA!  I'll setup some testbed and try and figure it out.

**Pull request merged**
