### PR TITLE
Auto bounce detection

### PR DESCRIPTION
**Pull request by Targren**
(Take 2)

Implemented new "Never" option for notifications (Magic Number 99)

Implemented code to automatically change notification_regularity to 99
on receipt of a DSN, with options to control the feature.

Outstanding needs:
Non-standard DSNs/bounces detection is still a stub
Member is not yet notified when emails are enabled

### CODE REVIEW

**Comment by Spuds** [comment]
Looks like you may want to rebase your auto_bounce_detection branch.  Not sure why travis failed the first time (5.4/postgre/curl) but it cleared up on a restart of that job.

**Comment by Targren** [comment]
I thought I did... like 6 times. :P Still having trouble with using git properly, obviously.

**Comment by Spuds** [comment]
Make sure you rebase it on to the elkarte/development branch (in case you rebased it on your local version of the development branch, or update your local development branch and then rebase this branch to that) .. Don't worry about fighting with github, everyone, and I mean everyone, goes through this :smile:

**Comment by Targren** [comment]
I think I may have mixed the two...rebased to elkarte/dev one time, then mine/dev without rebasing that.. but I'm not sure. I had to reclone my fork in order to get a pull request that wasn't a mess.

**Comment by Targren** [comment]
I wish I knew what was going on with those Travis builds.

**Comment by emanuele45** [comment]
Travis is probably just the "usual" buglet due to elk.net not letting search twice in a row... or maybe something else, I didn't check too deeply, but restarting it gave the green light, so it's fine. :P

If you need any help with rebasing or if I have to rebase it for you (I'm rather used now to rebase after having messed up a ton of stuff LOL) let me know. ;)

**Comment by emanuele45** [comment]
Merged in #2013 so I'm closing this one.

Thanks @Targren for the work! :D

**Pull request closed without merging**
