### PR TITLE
Make it possible to develop without removing the install directory

### PR DESCRIPTION
**Pull request by joshuaadickerson**
* add a check for $ignore_install_dir so we can develop without removing the install directory.
* Also adds a global variable, $settings_loc which is the full file path to the Settings.php file.

See: http://www.elkarte.net/community/index.php?topic=2885

### CODE REVIEW

**Comment by joshuaadickerson** [comment]
Hmm... I should have branched. Woops.

**Comment by emanuele45** [comment]
hmm...
conflicts...

Are all the commits relevant?

**Comment by joshuaadickerson** [comment]
No, only the first. I didn't branch so they got added. The rest are undefined indices I found

**Comment by emanuele45** [comment]
hmm... I'll have a look this evening.

**Comment by emanuele45** [comment]
I replaced this with #2224, so I'm closing this one.

**Pull request closed without merging**
