### PR TITLE
Some more 1.1.7 updates and fixes

### PR DESCRIPTION
**Pull request by Spuds**
Why are you reading this, does anyone read this? Just see the commits instead.

### CODE REVIEW

**Comment by Spuds** [comment]
Well that is a gigantic pain in the ass
What the F allows that to, not only run fine, but be required to even run , on my local only to have travis crap its pants .  I guess I'll deal with the tomorrow, maybe, right now I'm just pissed.

**Comment by Spuds** [comment]
Thats enough for this PR, so if you like it and don't see any errors .....

**Comment by emanuele45** [comment]
Maybe do you want to add also #3385 or should I not be **that** lazy and push them myself?

**Comment by Spuds** [comment]
No problem, I'll add them in ... 

I also have a pass of the one click unsubscribe about ready for review, and in doing that found a couple of more minor notify/mention bugs that I fixed i(n that branch though)

**Comment by Spuds** [comment]
Why you clever bastard !!! Now I see why you wanted me to add them LOL!

**Comment by emanuele45** [comment]
That was unintentional!! :laughing:

**Pull request merged**
