### PR TITLE
One more German file, first time with a sign-off (not configured well, I guess...) ^^

### PR DESCRIPTION
**Pull request by dertuxmalwieder**

### CODE REVIEW

**Comment by wintstar** [comment]
Is This still relevant?

**Comment by dertuxmalwieder** [comment]
Since the ElkArte team decided to move everything to Transifex where someone else already had a different, worse translation: no :(

**Comment by Spuds** [comment]
I thought both versions were on Transifex ... formal and ... don't know conversational?

**Comment by wintstar** [comment]
I've looked at a little bit. My impression is that this is no longer current. So my request.

**Comment by dertuxmalwieder** [comment]
I haven't updated this PR in ages, emanuele convinced me to go to Transifex where I, at least, have got some review capabilities by him.

So yes, this is old. 

@spuds Which of the two translations is mine, actually?

**Comment by eurich** [comment]
German (Germany) is Yours..

**Comment by emanuele45** [comment]
Ook, so this PR that was kept open for reference can be closed I guess.

**Pull request closed without merging**
