### PR TITLE
Various PHP 5.3 things and code cleanup

### PR DESCRIPTION
**Pull request by Vekseid**
Also moved some common constants in the installer to a new file, preferably for common code between the installer and upgrader.

The SITE_SOFTWARE thing may be debatable, but I figured it would be good if you e.g. moved elkarte.net to https.

### CODE REVIEW

**Comment by emanuele45** [comment]
Thanks. :dancers:

**Comment by emanuele45** [comment]
@Spuds any idea why travis keeps saying the build fails?
https://travis-ci.org/elkarte/Elkarte/builds/52180932

**Comment by Spuds** [comment]
Right now Travis is under maintenance so I'll have to take a look later.

**Comment by Vekseid** [comment]
Only the PHP 5.4 test and only under mysqli...

----

JavaScript error: file:///tmp/anonymous8155021745692810448webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js, line 11464: TypeError: this.server_ is undefined

JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_RETURNED_FAILURE) [nsIJSCID.createInstance]

**Comment by Spuds** [comment]
Its an incompatibility with FF36 and  the selenium WebDriver.  I updated the driver to 2.44.0 but that did not help.  It appears there is a 2.45 coming soon that will fix the issue.  There is a 2.45 dev3 version but I did not see a repo for the jar file so for now, expect the 5.4/mysql tests to fail when doing webtests.

When I see the 2.45 release I'll update the test config.

**Comment by Spuds** [comment]
2.45 was released last night, updated to test to use it and all seems to be back to normal.

**Comment by emanuele45** [comment]
YAY! :D

**Comment by emanuele45** [comment]
[This](https://travis-ci.org/emanuele45/Dialogo/builds/52614220) failure seems related to this, should I do anything?

**Comment by Spuds** [comment]
Yes, make sure you update your test directory in your local or you will still be using the old 2.43 jar file :angel:

**Comment by emanuele45** [comment]
ohhh... okay, I probably rebased the branch just after the dev_up... oh well, I can live with a broken test, but I can't deal with another rebase. :stuck_out_tongue:

**Pull request merged**
