### PR TITLE
Grinding away!

### PR DESCRIPTION
**Pull request by Spuds**
Added a implicitWait to web tests in hopes it stabilizes it.
Change quote logic/css 
Convert a few more icons to svg
ILA was not using the mime image in posts only preview
tweaked the attachment headers a bit,  empty Pragma was just strange and Content-Transfer-Encoding: binary for only gecko must be old or just cargo coding.

### CODE REVIEW

**Comment by emanuele45** [comment]
Fine to bring it in?

**Comment by Spuds** [comment]
I think so, easy enough to open another one ... right now I'm trying to get a v1.5.1+ version of the editor working, that will be another PR anyway.

**Comment by emanuele45** [comment]
I wasn't sure if you wanted to test anything on the wait for the tests. :D

**Comment by Spuds** [comment]
So far adding the implicit wait seems to have helped with the selenium fails 🙏

**Pull request merged**
