### PR TITLE
fix bug profile fields changes

### LINKED ISSUE #2593: change gender
ElkArte 1.1

index.php?action=profile;area=forumprofile

you have a sex change in the profile (maybe only my problem)

### PR DESCRIPTION
**Pull request by interlab**
fix #2593

### CODE REVIEW

**Comment by emanuele45** [comment]
The main issue was that they were set enabled in the install script f1521b6f22fc253b9f86f9403b8afecbb4c8da16

That said, I feel you are probably right saying the profile fields should be enabled by default.
Now I'm not sure if merge this one and fix it by enabling the fields and disable them... lol
Probably the best option is:
1) merge this and have CP on by default,
2) deactivate some of the existing fields (like most of the social sites and the very old AOL, etc.)

**Comment by interlab** [comment]
do as you like. 
the gender of the user and the location can be done enabled by default.
don't know.

**Comment by emanuele45** [comment]
Yes, that's what I thought as well.

**Comment by emanuele45** [comment]
In 6a8c573bf099c10386ea0b4978b0a7d867913851 I disabled the "social" custom fields (kept active location, gender and alike).

**Pull request merged**
