### PR TITLE
Few fixes for the attachments... and the theme

### PR DESCRIPTION
**Pull request by emanuele45**

### CODE REVIEW

**Comment by live627** [comment]
99 little bugs in the code 
99 little bugs 
Take one down, patch it around 
127 little bugs in the code

**Comment by live627** [comment]
@Spuds is alive!

**Comment by emanuele45** [comment]
HE IS! :laughing:

**Comment by Spuds** [comment]
Currently enjoying H3N2

**Comment by live627** [comment]
I just had it a week ago. First cold in years. It sucks.

**Pull request merged**
