### PR TITLE
First pass at theme stuff

### PR DESCRIPTION
**Pull request by Spuds**
Sure to break some stuff, be warned !

This is the color palette reduction
Removal of all bg bg2 divs
Removal of strong wrapped labels
Start of some css formatting, order of attributes
Very start of some template tweaks
Removal of some unused css classes
Removal of ie8 specific tweaks
More common template formatting / wrapping

Lots more to do, but since this was getting to big wanted to get in in now before I continue.

### CODE REVIEW

**Comment by Spuds** [comment]
Fixed web testcase due to class removal

**Comment by Spuds** [comment]
Awesome broke another web test case :+1:  to fix in the AM

**Comment by emanuele45** [comment]
lol

Hey! You fixed it! :P

**Comment by Spuds** [comment]
Awesome, its merged!  Now on to some more css/template abuse ! 

Of course be on the lookout for theme bugs, I tried to be somewhat careful, but you know how it goes when you are trying to clean things up ... easily distracted by opportunities and forget to complete some tasks :innocent:

**Pull request merged**
