### PR TITLE
Fixlets

### PR DESCRIPTION
**Pull request by emanuele45**
First round of bugs reported by @tomreyn
These are the easy ones, the others will have to wait a bit more. :P

### CODE REVIEW

**Comment by tomreyn** [comment]
#2624 wasn't reported by me but by @h-collector , so that's in-excess credit.

**Comment by emanuele45** [comment]
Ouch, copy&paste fault. :P 
Fixed and thanks for reporting! :D

**Comment by Spuds** [comment]
Time to merge this in ... rebase if you want to add more to this branch

**Comment by emanuele45** [comment]
TBH I forgot about it, otherwise I was going to merge it myself. lol
I think it was fine to merge. :smile_cat:

**Pull request merged**
