### PR TITLE
minor 1.0.10 adjustments

### PR DESCRIPTION
**Pull request by Spuds**
Couple of more items for 1.0.10 ... lets see if scruit fires on this one (which through much pain its working again)

### CODE REVIEW

**Comment by emanuele45** [comment]
nope... :sob:

**Comment by emanuele45** [comment]
I'm wondering if it makes sense to keep sensiolab when it fails every two or three checks... :-\

**Comment by emanuele45** [comment]
BTW
/me feels it's time to start preparing the patch... :sob:

**Comment by Spuds** [comment]
Seems sensiolab  only dies on the "master" or "patch" branches ... seems to run fine on development.  Yeah the patch should be getting close, there are the "other items" to add as well 🔒

**Pull request merged**
