### PR TITLE
Notifications

### PR DESCRIPTION
**Pull request by emanuele45**
At that point I feel it's time to get some feedback.
Here it is a slightly improved notification system.
It's still missing quite a lot of stuff, but it works (I hope :stuck_out_tongue: ).

Important bit:
https://github.com/elkarte/Elkarte/blob/b3422b62723d064bc4d4662e53dc516ee7db68f9/sources/subs/Notifications.class.php
the main Notifications class, the one that should coordinate the work.

Entry point is the add method, that accepts as parameter a [Notifications_Task object](https://github.com/elkarte/Elkarte/blob/b3422b62723d064bc4d4662e53dc516ee7db68f9/sources/subs/NotificationsTask.class.php), nothing more than a "bag" with some custom methods to retrieve some stuff we may need later.

Central point is the send method. Here each task (i.e. mention or new reply notification, etc.) is processed independently:
* 1st the mentionType object (those in sources/subs/MentionType) is instantiated ([line 57](https://github.com/elkarte/Elkarte/blob/b3422b62723d064bc4d4662e53dc516ee7db68f9/sources/subs/Notifications.class.php#L57))
* 2nd the members to be notifies are determined (I'm a bit unsure yet how that happens, but it's a WIP, for the moment it's at [line 62](https://github.com/elkarte/Elkarte/blob/b3422b62723d064bc4d4662e53dc516ee7db68f9/sources/subs/Notifications.class.php#L62))
* 3rd it works out what kind of notification/s each member wants (none, simple notification (the mentions area), notification + email, etc., [line 63](https://github.com/elkarte/Elkarte/blob/b3422b62723d064bc4d4662e53dc516ee7db68f9/sources/subs/Notifications.class.php#L63))
* 4th for each frequency, it 1) gets the "message" (body and subject) from the mentionType object ([line 69](https://github.com/elkarte/Elkarte/blob/b3422b62723d064bc4d4662e53dc516ee7db68f9/sources/subs/Notifications.class.php#L56)), 2) sends/inserts each of them ([line 77](https://github.com/elkarte/Elkarte/blob/b3422b62723d064bc4d4662e53dc516ee7db68f9/sources/subs/Notifications.class.php#L56))

To have an idea of how MentionType classes look like, I think that the buddies one is the best:
https://github.com/elkarte/Elkarte/blob/b3422b62723d064bc4d4662e53dc516ee7db68f9/sources/subs/MentionType/BuddyMention.php
just because it's the easiest, all the others had to hook into some action to do their work mixing the actual notification part with some other work.

Special mention is for the [Mentioning](https://github.com/elkarte/Elkarte/blob/0f4d2a1a59b18d981dca5483b36306bab958e1ea/sources/subs/Mentioning.php) class (and the name of the file is wrong...) that takes care of doing some validation and actions on the mentions themselves (i.e. log_mentions that means the mentions are in the menu).

It's not yet ready, it still misses all the user interface to configure the settings, but at least it "works" (mostly I guess LOL).

### CODE REVIEW

**Comment by emanuele45** [comment]
That's funny, I'll restart it tomorrow and see.

**Comment by Spuds** [comment]
Tried a restart ... seems its the web tests that are failing http://i.imgur.com/WYI6bGM.png and PHPUnit_Framework_Exception: Fatal error: Call to undefined method Errors::display_db_error() in /var/www/sources/database/Db-mysql.class.php on line 78  hummm

**Comment by emanuele45** [comment]
hmmm...
it may be related to https://twitter.com/traviscistatus/status/592902357144498176
Let's see after the rollback.
Otherwise I don't understand why only one out of 6...

**Comment by Spuds** [comment]
Could be .. but only 5.4 runs the selenium webtests and the code coverage reports, thats why it takes so much longer than the other test beds.

**Comment by emanuele45** [comment]
It likely is.
For curiosity I tested an old already merged PR and it breaks as well:
https://travis-ci.org/elkarte/Elkarte/jobs/59643301
I guess we have to wait a bit more to have back the green light.

**Comment by Spuds** [comment]
Guess we can wait till they rollback the updates this PM and see what that brings.

**Comment by Spuds** [comment]
I figured the update PR may break this ones ability to merge ... should be a simple conflict I hope

After its fixed I think its time to merge this one in as well.

**Comment by emanuele45** [comment]
Rebase'ed and pushed. :hamster:

**Comment by Targren** [comment]
Should this be labeled as a block, since it's pretty much all I'm still waiting on in #1968 (the non-standard DSNs can be handled when the rest of the function is in place) which *is* labelled as a block.

**Comment by emanuele45** [comment]
Well, yes, we can label this as a blocker, but it's already merged in the development branch, so already in 1.1.

**Comment by Targren** [comment]
Oh, well if it's done, then I guess I have some work to do. Wish I'd caught it sooner. :)

**Comment by Targren** [comment]
I'm still having trouble getting notifications going for testing, even without making any changes. I've got them turned on in the forum features, and I've got the preferences for each type turned on in the database ({$user, 1, $type} in elkarte_notifications_pref) but not mentions, buddy, nor quotes are sending any notifications. I'm guessing I missed something.

**Comment by Spuds** [comment]
I'm going to guess, and this really is nothing more,     that the event "triggers" were not registered in the db.  I think they are in the install or the update file, can't remember.  

But I seem to remember some values need to be set during install and they are not set / reset / fixed when you hit save from the ACP (at the current time).

**Comment by Targren** [comment]
I'll check that out. Thanks.

**Comment by emanuele45** [comment]
Did you already try to turn them off and on again?
Do notifications popup in the mentions area or not even there?

**Comment by Targren** [comment]
No, I saw no notifications anywhere

**Comment by emanuele45** [comment]
I have the terrible feeling I forgot to add a require_once... :astonished: 
In Notifications.class.php, add a:
```
		require_once(SUBSDIR . '/Mail.subs.php');
```
just before:
```
		$notification_frequencies = filterNotificationMethods($this->_notification_frequencies, $class::getType());
```

Let me know if that makes any difference (in my case it did).

**Comment by Targren** [comment]
Doesn't seem to be helping me, but it's entirely possible I didn't so something. 

I've got "Enable site Notifications" turned on (and off, and on) and "Enable User Notification of This Event" for all event types.  Then I make a post with one test user, log in with another test user, and quote it, @ it, and like it.  The first user's notifications stay empty. I'm using two separate browsers to make sure that there's no session-clobbering or anything like that.

**Comment by emanuele45** [comment]
Is it a fresh install or did you overwrite the files of an existing dev branch? (Or other alternatives?)
No errors in the log?

**Comment by Targren** [comment]
Brand new install on a brand new VM. The only things in the error log are the aforementioned "Unidentified Index" notices from getTimeLastMention()

**Comment by emanuele45** [comment]
Ouch, I didn't notice the updates.
That undefined are likely because nothing is inserted (and it's a bug because it should not return an undefined index anyway => tracked #2422), now I have to try a new install and see what's wrong.
This evening (in ~7 hours).

**Comment by emanuele45** [comment]
Sorry, I've lost a lot of time on another thing, will take care of this in the morning... :sob:

**Comment by Targren** [comment]
No worries. I'm not in any terrible rush. :) 

On March 8, 2016 6:48:57 PM EST, "emanuele45 - notifications@github.com" <git.geekciro.9ba53f7d18.notifications#github.com@ob.0sg.net> wrote:
>Sorry, I've lost a lot of time on another thing, will take care of this
>in the morning... :sob: 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/elkarte/Elkarte/pull/2049#issuecomment-194028190

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by emanuele45** [comment]
Okay, I was able to debug it.
Could you check Subs.php, in the obExit function, there should be this piece:
```

	// Clear out the stat cache.
	trackStats();

	// If we have mail to send, send it.
	if (!empty($context['flush_mail']))
		// @todo this relies on 'flush_mail' being only set in AddMailQueue itself... :\
		AddMailQueue(true);

	Notifications::getInstance()->send();

	$do_header = $header === null ? !$header_done : $header;
```

move the ```Notifications::getInstance()->send();``` up before the AddMailQueue if block like this:
```

	// Clear out the stat cache.
	trackStats();

	Notifications::getInstance()->send();

	// If we have mail to send, send it.
	if (!empty($context['flush_mail']))
		// @todo this relies on 'flush_mail' being only set in AddMailQueue itself... :\
		AddMailQueue(true);

	$do_header = $header === null ? !$header_done : $header;
```

**Comment by Targren** [comment]
No dice, but I'm wondering if we might be at cross purposes here. I can't
get notifications/mentions to work at all - not just for the email disable
notice, but not for quotes, @mentions, nothing. I've been trying to do that
since I can't be sure if the disable notice is broken until I can make the
rest of the notifications work like they're supposed to. It may well be
that I missed some step somewhere, or some combination of settings isn't
just quite right.

On Wed, Mar 9, 2016 at 3:02 PM, emanuele45 - notifications@github.com <
git.geekciro.9ba53f7d18.notifications#github.com@ob.0sg.net> wrote:

> Okay, I was able to debug it.
> Could you check Subs.php, in the obExit function, there should be this
> piece:
>
>
>     // Clear out the stat cache.
>     trackStats();
>
>     // If we have mail to send, send it.
>     if (!empty($context['flush_mail']))
>         // @todo this relies on 'flush_mail' being only set in AddMailQueue itself... :\
>         AddMailQueue(true);
>
>     Notifications::getInstance()->send();
>
>     $do_header = $header === null ? !$header_done : $header;
>
> move the Notifications::getInstance()->send(); up before the AddMailQueue
> if block like this:
>
>
>     // Clear out the stat cache.
>     trackStats();
>
>     Notifications::getInstance()->send();
>
>     // If we have mail to send, send it.
>     if (!empty($context['flush_mail']))
>         // @todo this relies on 'flush_mail' being only set in AddMailQueue itself... :\
>         AddMailQueue(true);
>
>     $do_header = $header === null ? !$header_done : $header;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elkarte/Elkarte/pull/2049#issuecomment-194480672>.
>



-- 
"The nitrogen in our DNA, the calcium in our teeth, the iron in our blood,
the carbon in our apple pies were made in the interiors of collapsing
stars. We are made of starstuff." - Carl Sagan

**Comment by emanuele45** [comment]
True enough, the @ and quote mentions are not "really" enabled at install (I noticed just now and applied the fix, will push later on), though, following this procedure:
* go to *admin > config > features and options > notifications*
* remove the tick from the "Enable user notifications of this event." corresponding to @ and quote mentions
* save
* add again the tick
* save

the mentions start to work as expected for me, and with the change suggested above the emails are sent as well (well, I checked they land in the mail_queue table, but considering all the other emails should be delivered those should go as well... unless there is a bug in the sending of email).

Tomorrow I'll set up an open test site, so we can try it out live.

**Comment by Targren** [comment]
Awesome, that made quoting work, so now I've got a baseline. I've got
server updates and maintenance tying me up most of the next few days, but
I'll see what I can squeeze in.

On Wed, Mar 9, 2016 at 4:36 PM, emanuele45 - notifications@github.com <
git.geekciro.9ba53f7d18.notifications#github.com@ob.0sg.net> wrote:

> True enough, the @ and quote mentions are not "really" enabled at install
> (I noticed just now and applied the fix, will push later on), though,
> following this procedure:
>
>    - go to *admin > config > features and options > notifications*
>    - remove the tick from the "Enable user notifications of this event."
>    corresponding to @ and quote mentions
>    - save
>    - add again the tick
>    - save
>
> the mentions start to work as expected for me, and with the change
> suggested above the emails are sent as well (well, I checked they land in
> the mail_queue table, but considering all the other emails should be
> delivered those should go as well... unless there is a bug in the sending
> of email).
>
> Tomorrow I'll set up an open test site, so we can try it out live.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elkarte/Elkarte/pull/2049#issuecomment-194516529>.
>



-- 
"The nitrogen in our DNA, the calcium in our teeth, the iron in our blood,
the carbon in our apple pies were made in the interiors of collapsing
stars. We are made of starstuff." - Carl Sagan

**Comment by emanuele45** [comment]
YAY!

**Pull request merged**
