### PR TITLE
A bunch of tests

### PR DESCRIPTION
**Pull request by emanuele45**
Some more tests for our beloved BBCode parser! :dancers:

### CODE REVIEW

**Comment by Spuds** [comment]
I'm assuming the B2 milestone means wait to merge.

**Comment by emanuele45** [comment]
I'm adding some more, but the B2 means... no idea. xD

**Comment by emanuele45** [comment]
And that's all for now.
The only missing is quote because it has too many variants... :confounded: 

@joshuaadickerson FYI :stuck_out_tongue:

**Comment by joshuaadickerson** [comment]
That's not all of them, right?

**Comment by joshuaadickerson** [comment]
You can set tests to fail and continue. That would be better than allowing the bug. It should bug us ;)

**Comment by emanuele45** [comment]
The only not tested (yet) are the various forms of the quote tag.

**Comment by emanuele45** [comment]
YAY!
Added (most of) the quote variants too.

**Pull request merged**
