### PR TITLE
Update Index.css - Group Options display

### PR DESCRIPTION
**Pull request by LouAugust**
This will the width and stop the truncating of lines. All options will now display on a single line.

### CODE REVIEW

**Comment by Vekseid** [comment]
Shouldn't this go into admin.css?

**Comment by LouAugust** [comment]
It could; the #admin_form_wrapper part could force it into admin.css.  Might be more of a toss up though. I placed these where the original '.settings' were being called. I have no problems if that is where he wants it; he can close this commit and I will resubmit with it in admin.css. I am good with that. :smiley:

**Comment by Vekseid** [comment]
I figured the idea was to trim down the monstrous size of the global css file >_>

**Comment by joshuaadickerson** [comment]
Yeah. I think it makes sense in admin.css but congrats on getting your first PR done

**Comment by LouAugust** [comment]
:)  No problem. I will close this and resubmit the changes in admin.css.  thanks

**Pull request closed without merging**
