### PR TITLE
This removes the location, gender, and personal text custom fields

### PR DESCRIPTION
**Pull request by Vekseid**
also adds an 'above icons' custom field location to enable mimicking old, slightly more flexible behavior.

This is part one of a three-stage resolution for #1322. It just touches a lot of files so I wanted to merge one component at a time.

'Website' unfortunately still remains as a standard field, and 'custom title' is also a bit suspect. A proper custom personal text replacement would also need defaults as described in #2393.

### CODE REVIEW

**Comment by Vekseid** [comment]
Ugh, looks like I missed something when altering the member table. Hrm

**Comment by Vekseid** [comment]
That insert format is so obnoxious I am tempted to just rewrite it. I am not sure why it's failing since this is the error I solved with the latest commit, though. : /

**Comment by emanuele45** [comment]
I think you missed the one in ```tests/travis-ci/setup.php```, there you removed only the fields from the first array and not from the second.

**Comment by Vekseid** [comment]
Well that was embarrassing.

Is there some reason the install script (and its test) do the member insert like that?

**Comment by Vekseid** [comment]
Any further comment on this?

**Comment by emanuele45** [comment]
The only thing I do not see is the code to deal with the upgrade process.
Do we want to merge and deal with that part later?

**Comment by Vekseid** [comment]
That's my current plan. #1322 needs icon work (separate) and if we can do something for #2393, that changes what the upgrade path would look like a bit.

**Comment by emanuele45** [comment]
Ohh, okay I see it.

**Pull request merged**
