### PR TITLE
First batch of fixes for 1.1.5

### PR DESCRIPTION
**Pull request by emanuele45**

### CODE REVIEW

**Comment by Spuds** [comment]
Looks like the travis error is the same deep cody 1.8.1 that we had to adjust for in the Dev branch.

**Comment by emanuele45** [comment]
@Spuds I'm a little lost here.
All the tests run properly except one postgre. At first it was the one with php 5.6, not is php 7.1.
Apparently at a certain point it's not able to retrieve correctly the data from the database.
I tried to debug it a bit and querying the db from the test script returns the content of the members table properly, while querying the do from Load.php doesn't return anything (see my latest comment where I fetch the content from Auth.subs.Test.php the line before loadMemberData and I get content, while, just stepping inside loadMemberData no data are returned.
I'm lost.

**Comment by Spuds** [comment]
I was trying to determine what you were doing 😇 After deep cody was set to 1.8.0 it looks like the tests ran fine  ... am I missing something?

**Comment by emanuele45** [comment]
@Spuds one of the postgre tests is always failing:
https://travis-ci.org/elkarte/Elkarte/builds/406938512?utm_source=github_status&utm_medium=notification
in particular:
https://travis-ci.org/elkarte/Elkarte/jobs/406938545#L827
```
Starting test 'TestAuthsubs::test_login_cookie'.
F
```

The test fails because the query in loadMemberData doesn't find anything in the {db_prefix}members table (the table seems completely empty).
What I did (at least) was add a query:
```
		print_r($db->fetchQuery('SELECT id_member, member_name, real_name
		FROM {db_prefix}members'));
```
in the test_login_cookie function just before the call to loadMemberData and the same at the beginning of loadMemberData.
From the query in test_login_cookie the table *has* data, from the query in loadMemberData the table *doesn't* have any data.

**Comment by emanuele45** [comment]
So, currently we have:
https://travis-ci.org/emanuele45/Dialogo/builds/407331261
the only test failing is test_login_cookie with any postgre and php 5.6 and 7.1.
This is the only test using @runInSeparateProcess.
Apparently:
1. in php 5.6, the db doesn't contain data during the entire test_login_cookie test (index 2 of the array):
https://travis-ci.org/emanuele45/Dialogo/jobs/407331268#L1244
https://travis-ci.org/emanuele45/Dialogo/jobs/407331269#L1233
https://travis-ci.org/emanuele45/Dialogo/jobs/407331270#L1233
2. in php 7.1 the db contains data *before* the call to loadMemberData (index 2 of the array):
https://travis-ci.org/emanuele45/Dialogo/jobs/407331271#L833
https://travis-ci.org/emanuele45/Dialogo/jobs/407331272#L833
https://travis-ci.org/emanuele45/Dialogo/jobs/407331273#L833
but not inside the call to loadMemberData (index 2 of the array):
https://travis-ci.org/emanuele45/Dialogo/jobs/407331271#L859
and not even after being "back" inside test_login_cookie (index 2 of the array):
https://travis-ci.org/emanuele45/Dialogo/jobs/407331271#L885

**Comment by emanuele45** [comment]
I'm almost tempted to say: let's disable the test.

**Comment by Spuds** [comment]
Whats extra strange is that when you did the deep cody fix, Travis ran fine in the Elkarte Repo ( https://travis-ci.org/elkarte/Elkarte/builds/406820107?utm_source=github_status&utm_medium=notification )  but Failed on your Dialogo repo ( https://travis-ci.org/emanuele45/Dialogo/builds/406819931?utm_source=github_status&utm_medium=notification )

**Comment by Spuds** [comment]
I tried a few things and made no progress on why that one test under that php/pgsql version fails.  I'm also inclined to disable that test or skip it for that "combo"

**Comment by emanuele45** [comment]
From the last try I had at it:
https://travis-ci.org/elkarte/Elkarte/builds/407815341
it's a series of version conflicts and problems with the @runInSeparateProcess
In other words, when I removed all the constrains on versions we have in composer.json except for myclabs/deep-copy everything run smoothly (except for PHP 7.1 choking on (yet) another issue).
Since the development branch **seems** to work fine, I'll just remove this test for the time being.

**Pull request merged**
