### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by emanuele45**
Make sure to merge #2250 first, this one is easy to rebase in case of conflicts! ;D

### CODE REVIEW

**Comment by Spuds** [comment]
Conflicts !!! (sorry, I knew that would happen)

**Comment by emanuele45** [comment]
No problem, it shouldn't be that hard to rebase... I hope. lol

**Comment by emanuele45** [comment]
Fixed! :D

**Comment by Spuds** [comment]
:bomb: Class 'Search' not found in /var/www/sources/subs/Search.subs.php on line 42

**Comment by emanuele45** [comment]
ehhh... when you start using namespaces it's so easy to make mistakes! LOL
Though they are quite nice. **nods**

**Pull request merged**
