### PR TITLE
Fix random things

### PR DESCRIPTION
**Pull request by Spuds**
Still trying to prep a 1.1 B1  ... needs moar work

### CODE REVIEW

**Comment by emanuele45** [comment]
heh...
Apparently the testing of the headers is slightly too picky...
It should be enough to test for \s (spaces) instead of the exact sequence of spaces and tabs:
https://github.com/elkarte/Elkarte/blob/development/tests/sources/FilesTest.Basic.php#L110
https://github.com/elkarte/Elkarte/blob/development/tests/sources/FilesTest.Basic.php#L111
and so on... would you like to do the honors? :innocent:

**Comment by Spuds** [comment]
LOL ... I was doing just that when you entered the comment ... I used /s+? which should cover spaces and tabs, any number, any combo ... lets see what it thinks now

**Comment by Spuds** [comment]
Worked .. Travis gave me a :trophy:

**Comment by emanuele45** [comment]
In that one as well! :tada:

**Pull request merged**
