### PR TITLE
2017 Preparation Update

### PR DESCRIPTION
**Pull request by Trekkie101**
- Remove redundant calendar entries
+ Add St. Andrew’s Day
* Clarify which independence day
* Update copyrights

### CODE REVIEW

**Comment by emanuele45** [comment]
/me takes note we should implement a better way to deal with this kind of stuff... :-\

Thanks!

**Comment by Trekkie101** [comment]
For the copyright dates, it could just be date('Y') or remove them entirely, not sure they're really relevant but helps show how long the project has been about. Only flaw with date() is a misconfigured server. 

Potentially for the holidays:
1) We could over engineer a tool to make the recurring but not 'set' dates.
2) Remove them - since I doubt anyone uses them
3) Remove non 'set' dates and instead add more fixed date holidays.

**Comment by cody3647** [comment]
Would there be a way to use relative date formats...that would cover most non-set date holidays I would think.

**Comment by emanuele45** [comment]
When I wrote the comment I was thinking about a kind of flexible relative date based on month/weeks, what you are used to see in a calendar app: set an even every 1st Sunday of the month, every 1st Sunday of July, on Tuesday every other week, etc.

**Pull request merged**
