### PR TITLE
Front page

### PR DESCRIPTION
**Pull request by emanuele45**
Ohhh.... whatever!
The code to allow use any controller (that supports the feature) as front page and as a plus the starting of the release automation.

### CODE REVIEW

**Comment by Spuds** [comment]
Is this all set to merge?  (was not sure based on your comments on the site)

**Comment by emanuele45** [comment]
There is the settings bug, yes. I have to take care of it.
About functionality, I plan to add more controllers while we go, also because I don't think **many** will be suitable to appear on the front page (I think display is the only still worth probably).

**Comment by emanuele45** [comment]
Rebased and fixed the bug.

**Comment by Spuds** [comment]
Scruit or travis is timing on on the clover reports .. oh well

**Pull request merged**
