### PR TITLE
Starttls support and base64 fix

### LINKED ISSUE #2276: STARTTLS Support in Elkarte
Sooo I've finally started moving some of my communities over to Elkarte and ran into this. "Still waiting on my email" "...oh."

The fix is still pretty much as described here:
http://www.simplemachines.org/community/index.php?topic=180532.msg1148462#msg1148462

But it would probably be wise to wrap it in a setting.

### PR DESCRIPTION
**Pull request by Vekseid**
Resolves #2276 and #2282

### CODE REVIEW

**Comment by Vekseid** [comment]
Ugh, and I thought I cleared out the newbishness : /

**Comment by emanuele45** [comment]
lol

git is picky :stuck_out_tongue: 

If you want I can cherry-pick the commit in one of the next PRs of mine. ;)

**Comment by emanuele45** [comment]
@Vekseid I cherry-picked it at #2287 and changed a bit the commit message to reflect what the commit is about (just because with a meaningful commit message it's easier to search the history if needed ;) ).

And thanks for the patch! :D

**Comment by Vekseid** [comment]
@emanuele45  good for me to close this then?

I think phpstorm dun goofed my fork. Ugh.

Oh well. Plenty to do, for sure.

**Comment by emanuele45** [comment]
From the commit messages it looks like you "merged" the elk repo into your local repo.
I guess (but since it's phpstorm @Spuds should have better knowledge than me) there should be a way to "pull" the repo without creating each time a merge commit.
Of course it's just pickiness on my side, otherwise the PR would be good. :+1: 

Anyway, yep, this can be closed. ;D

**Comment by Vekseid** [comment]
Yeah, I didn't create a proper rebase locally, so the branch was messed up. : /

**Pull request closed without merging**
