### PR TITLE
Added $db_type to bootstrap.php 

### PR DESCRIPTION
**Pull request by tinoest**
Fixed bug where its not set when calling bootstrap.php and therefor tries to use mysql as a default

### CODE REVIEW

**Comment by emanuele45** [comment]
Why that one was overlooked for so long?
Sorry @tinoest my fault... :blush:

**Comment by emanuele45** [comment]
A suggestion: usually it's better to use rebase to bring a branch in line with the main development one instead of using merge, this because it makes the history much cleaner (less "merge *** branch" in the history).

**Comment by tinoest** [comment]
Will try that next time, I'm still used to the svn way of merging and syncing with upstream if I'm honest.

**Comment by emanuele45** [comment]
No problem. :)

If you want to compare it to the "SVN-way", I think it's just a matter of replacing update (?) with rebase. (Well, maybe not **exactly**, but something like that, with some jumping between branches in addition. lol)

**Pull request merged**
