### PR TITLE
 Generate code coverage data during all runs 

### PR DESCRIPTION
**Pull request by live627**
Different runs cover different code. Gotta collect them all.

### CODE REVIEW

**Comment by emanuele45** [comment]
scrutinizer.yml was removed a while ago in favour of the config at the website.
Is there anything that should be changed?

**Comment by live627** [comment]
```
tools:
    external_code_coverage:
        timeout: 1800
        runs: 6
```

**Comment by emanuele45** [comment]
The external_code_coverage was changed, then it's time to merge I guess.

**Comment by live627** [comment]
>  Test Coverage has increased to 15% (+1%). 

Noice!

**Pull request merged**
