### PR TITLE
Misc fix Part II

### PR DESCRIPTION
**Pull request by Spuds**
Continuing on the updating to use http req class

Several bugs found along the way and hopefully fixed

Updated some some docblocks, mostly common param details for start, per page and sort, complements of S&R so look out :innocent:   Also some spell check things etc etc.

### CODE REVIEW

**Comment by Spuds** [comment]
@emanuele45 Your thoughts on this one, https://github.com/Spuds/Elkarte/commit/279db940f5fd216498f79bf17e758b15c403bcb9

This is very basic, but it allows JS to send json strings to the controllers.  This is done by posting a named variable (jsonString) the value of which is a JSON.stringify(obj) value from the script.  ( https://github.com/Spuds/Elkarte/commit/279db940f5fd216498f79bf17e758b15c403bcb9#diff-d271dde5b6ce40fd9052c434a0b4ceddL625 ) HttpReq class looks to see if its passed that sting, and then does a json_decode and places the results in the ->post object (thats not $_POST), its only in the object created in that class.  ( https://github.com/Spuds/Elkarte/commit/279db940f5fd216498f79bf17e758b15c403bcb9#diff-ee51dc566933a5ce3ce96f3c86b21ce3R133 )

Then in the controllers you can look for the post values instead of the get values like ( https://github.com/Spuds/Elkarte/commit/279db940f5fd216498f79bf17e758b15c403bcb9#diff-bf437c4bcc71653197fea8b5604e29aeR76 )

This one also updates the Suggest.class to used passed value in a constructor vs relying on context and post, nothing really to do with the above but you may see that in the mess !

**Comment by emanuele45** [comment]
Looks good to me! :smile:

**Comment by emanuele45** [comment]
I'm not sure if this is ready to go or you have to add more things! :innocent:

**Comment by Spuds** [comment]
Feel free to merge it in ... I still have a few more controller to go through but easy enough to open part III ... plus since this still merges :innocent: thats a bonus.  Takes us up to 4.4, I'm trying to get us to 4.5 !

**Pull request merged**
