### PR TITLE
Revert attachments in draft

### PR DESCRIPTION
**Pull request by emanuele45**
Sad, but I give up.
Save attachments for drafts is something that is far beyond the scope and possibilities of 1.1 unless we want to redo a lot of stuff.

In this PR I reverted the changes I made to try to save attachments for drafts as well, fixed the ILA (including preview) and added few default mime showing the appropriate icon.

Still some goodies are missing (like alignment, resizing, etc., but they can wait a bit, even a B2.

### CODE REVIEW

**Comment by Spuds** [comment]
:crying_cat_face: sorry you could not get it working, I know how that feels! ... what was the final straw on the :camel:  ?

**Comment by emanuele45** [comment]
Basically security.
Having to deal with attachments not associated to a topic saved in the database means they need another field "owner" or something similar to check against, so yet another mess of queries to change to test for ownership as well. A mess...
I think there is to re-think a bit the attachments database structure to have a higher level of flexibility (i.e. ditch the avatars from the attachments table, so that id_member becomes not something we rely on in order to find the avatar of a member, ditch the thumbnails, and probably more).

Oh, do not merge it yet, I missed some stuff!

**Comment by emanuele45** [comment]
Okay, that commit should do.

**Comment by Vekseid** [comment]
Yeah the way SMF/Elkarte/MyBB/phpBB handle attachments is so bad I just turn it off for any forums I run in the first place. >_>

**Pull request merged**
