### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by emanuele45**
Just some formatting (spaces to tabs) and a new test to check (c) headers are there and are formatted more or less the way we love them.

### CODE REVIEW

**Comment by Spuds** [comment]
Glad to have another code :trollface: is in da house !  :tada:

**Comment by emanuele45** [comment]
I was thinking about implementing an automated :trollface: for testing indentation, but is too much of an hassle.

**Comment by Spuds** [comment]
:trollface: : saz ... better to spend time on things that look like this instead :tongue: 
```
}

public function WhereAreMeDocBlocks(l$ots, $of, $params)
{
}
```

**Comment by joshuaadickerson** [comment]
Answer: New pedantic tests for formatting
Question: What happens when you submit a PR with spaces instead of tabs and missing headings?

I finally fixed PhpStorm so now it is following my settings. It even tells me now that files are indented with spaces instead of tabs and asks me if I want to fix them. I click a single button and it does it for me.

**Comment by emanuele45** [comment]
> Question: What happens when you submit a PR with spaces instead of tabs and missing headings?

Space <=> tabs: the blame history of the file is mostly broken because
that single commit changes the entire file (and probably moving the
file as well .
Yes, it should be the responsibility of the "merger" to ensure it
doesn't break, but people can do mistakes (/me is :innocent: lol) and
miss the problem.

Missing headers: well, in theory nothing, in practice inconsistency,
that is bad by itself. :P
If we were to consider moving from "header in each file" to "(c) in
LICENCE.txt" we'd have to face the fact SM requires explicitly that
SMF headers should be in each file, so we are not allowed (due to the
precedents with other projects we already know that).

**Pull request merged**
