### PR TITLE
Inline JS minification

### PR DESCRIPTION
**Pull request by Spuds**
This is a bit of an experiment. 

It allows us to use the "internal" squeeze to minify the standard and deferred Inline javascript that templates, sources, addons, etc add to the page.  This just adds (really separates and exposes) the code in Combiner that was available to do this.  Also adds a getInstance method to Combiner since we were invoking it a few times.

The plus side is that it will save a 1-2k per page load, the downside is that it will also add a few hundreds of a second to the page creation time.  I considered caching the results, but could not see a suitable "key" since whats often inline is unique to the user, and perhaps unique on each page load.

Also updated to the latest squeeze.

### CODE REVIEW

**Comment by Frenzie** [comment]
Wouldn't it be much more worthwhile to get rid of the inline stuff and to add it dynamically on DOMContentLoaded or some such? That would surely save at least as much (browser caching!) without any server issues.

**Comment by Spuds** [comment]
I suppose, but I have no real idea how to do that :/ ... You should open a feature request for this or better make a PR, there is a lot of source generated JS that is loaded to the page.   I'll close this one as not needed and await a better way to handle this.

**Comment by Frenzie** [comment]
Mostly it's just that I don't see 1-2 kB (is that before or after gzip?) as a worthwhile trade-off for hundreds of a second of extra processing time. But I actually misinterpreted this while I was distracted by the fact that my heater/boiler broke this morning. By default there seems to be about 2 kB of JS which is virtually incompressible through this method in the header and footer (I mean all the stuff like `likemsg_are_you_sure = 'You already liked this message, are you sure you want to remove your like?',`), while I was actually thinking of stuff that's just echoed and wouldn't be affected. Overall I just don't quite see how you'd get more than a couple hundred bytes out it (mostly by stripping whitespace) that you wouldn't also get with gzip?

**Comment by Spuds** [comment]
Bummer about the heater ... but its summer now, you have months to get that fixed :dancer: 

1-2k was a before vs after final page size, I don't recall which pages ATM, so probably more than just white space *shrugs*  Some pages have quite a bit of JS created in the sources and templates (some of which is erroneously not deferred), addons often add quite a lot.

No idea of the impact in the gzip size of the transport (will vary on several factors anyway such as web server used or php buffer based or none at all), nor cpu / time impact of the zip/unzip for the two base page sizes.

**Comment by Frenzie** [comment]
It's the shower that matters. ;)

**Comment by emanuele45** [comment]
Cold shower helps! :P

**Pull request closed without merging**
