### PR TITLE
Do not embed video links in the middle of sentences

### PR DESCRIPTION
**Pull request by Frenzie**

### CODE REVIEW

**Comment by emanuele45** [comment]
Thanks!
I guess we can bring that one in the coming 1.0.7 so that it is fixed "immediately"?

**Comment by Frenzie** [comment]
Sure, do you want me to submit another PR on the 1.0.7 branch?

**Comment by emanuele45** [comment]
I have already another tweak to add, I'll cherry-pick this commit as
well. ;D

**Comment by Frenzie** [comment]
While you're on it, I just wrote https://github.com/Frenzie/Elkarte/commit/a9513986684e57cc35e6d49f67255b418d9ea91f

**Comment by Frenzie** [comment]
Just playing around a bit with Elk to investigate an alternative upgrade path from SMF 2.0. =P

**Pull request merged**
