### PR TITLE
Just a test of testing

### PR DESCRIPTION
**Pull request by Spuds**
Just playing with trying to get controller testing done since there is no browser, login, session, etc.  Want to see what this does to the coverage.

### CODE REVIEW

**Comment by Spuds** [comment]
```The last posting from your IP was less than 0 seconds ago. Please try again later.``` WTF .7.3/postgre !
I tried both random IP's and zero waitime with the same fail.   @emanuele45 I assume this is a db abstraction error where its returning a value other than ```1``` for ```affected rows (security 1531)``` but I don't have any postgre setups to test on to fix this issue so could use some help.  

On another note, this simple test adds .8% to the coverage even though we test create post and likes already, but just the subs, not the controllers.

**Comment by emanuele45** [comment]
I'm looking into it.
Note that there is a bug in bootstrap.php:
```
if (defined('IGNORE_INSTALL_DIR'))
```
should be:
```
if (!defined('IGNORE_INSTALL_DIR'))
```

**Comment by emanuele45** [comment]
Anyway @Spuds I'm currently stuck with not being able to connect to the psql server. :-\
I'll keep trying...

**Comment by Spuds** [comment]
I did some abuse of Travis to help debug a bit.  What I *think* is occurring is that ```$this->_db_replace_result``` is being set in the PG insert function (part of the pgsql replace compatibility area) but after this section, right before the Result object is set
```
		if (!empty($data))
		{
			$last_inserted_id = $this->insert_id($table);
		}
```
the value of ```$this->_db_replace_result``` is reset to null, and that is what is returned in the Result object and then returned in ```affected_rows``` so the spam protection triggers at that point since it does not get a ```1``` back.

**Comment by Spuds** [comment]
Further looking has this section in the query function in Query.php (postgre)
```
		// One more query....
		$this->_query_count++;
		$this->_db_replace_result = null;
```
so this is where the results are nullified.  As a test I changed it to ```$this->_db_replace_result = $this->_db_replace_result ?? null;``` and the tests passes.  Not sure if that is the right thing, or changing the logic around in the insert function.

**Comment by emanuele45** [comment]
@Spuds I think the issue is with inser_id that does a query that should not be "counted" towards.
I think the easiest way should be to change:
```
$this->_db_replace_result = $db_replace_result + $inserted_results;
```
to:
```
$db_replace_result = $db_replace_result + $inserted_results;
```

and then:
```
'replaceResults' => $this->_db_replace_result,
```
to:
```
'replaceResults' => $db_replace_result ?? 0,
```

Here it works and **should** avoid side-effects. Maybe not all of them, though. :laughing:

**Comment by Spuds** [comment]
Is anything then setting ``` $this->_db_replace_result``` or would that always be null ?

**Comment by emanuele45** [comment]
@Spuds I guess it would not be set ever. Fair enough. :laughing: 
hmm... this is a pain in the arse... :-\
And actually, this is the only instance I could find that requires this hack in order to give "correct" results.
Considering how seldom (hopefully) this code would run, would it make sense to just have one more query and not rely on an insert replace?
Unless this could have implications also for example for SP.

**Comment by Spuds** [comment]
Doesn't postgre have a ```ON CONFLICT``` statement you can use on insert?  Could we use that or is that different altogether.  I'd be fine with another query, I'm not sure of the implications on SP, its been a while since I looked at the code 😇

**Comment by emanuele45** [comment]
Looking at the old SMF 2.1 code I have handy, this variable was never set to begin with... :thinking:

**Comment by emanuele45** [comment]
@Spuds what is the status of this one? Should be merged?

**Comment by Spuds** [comment]
Let it sit for a bit ... I don't have your suggested postgre db fix in this and have another test to push.  Got sidetracked on some 1.1.6 issues

**Comment by Spuds** [comment]
I'm done playing with this for now, going to merge it in as the updates will allow us to do some controller testing w/o having selenium running.  Not perfect nor exhaustive but a start.

**Comment by emanuele45** [comment]
:dancing_men: :dancing_women: :dancer: :man_dancing: :dancing_women: :dancing_men:

**Pull request merged**
