### PR TITLE
Search methods updeate

### PR DESCRIPTION
**Pull request by live627**
Simplifies code a little and make the API namespaces PSR-4 compatible.

Existing API calls should be returning the same results.

### CODE REVIEW

**Comment by emanuele45** [comment]
Conflicts...
Please try to use rebase and not merge. ;D

**Comment by emanuele45** [comment]
BTW, after that, I'd say let's keep the refactorng for 2.0, so we can flush out 1.1 ASAP. ;D
If we are confident, we could even branch 1.1 at the first RC and keep active development out of the release game, and at each step we can re-merge the fixes from 1.1 into dev the same way we do for 1.0 patches.

**Comment by live627** [comment]
Rebase completed.

**Comment by live627** [comment]
> If we are confident, we could even branch 1.1 at the first RC and keep active development out of the release game, and at each step we can re-merge the fixes from 1.1 into dev the same way we do for 1.0 patches.

I like that idea!

**Pull request merged**
