### PR TITLE
Some problems with like stats

### PR DESCRIPTION
**Pull request by emanuele45**

### CODE REVIEW

**Comment by Spuds** [comment]
We may consider moving this to stats in b2 ... I'm just not convinced its top menu worthy.

**Comment by emanuele45** [comment]
Yep, I think there was even an issue somewhere.

**Comment by Vekseid** [comment]
Was wondering why it had a top level menu item >_>

**Comment by Spuds** [comment]
The author of the original commit did it that way and it was never changed.  I was going to move it when I did some work on the functions but ran out of momentum.  We should get it sorted in the betas.

**Pull request merged**
