### PR TITLE
More dynamic group exclusion rules for inline permissions

### PR DESCRIPTION
**Pull request by live627**
/**
     * Configuration variables and values, for this settings form.
     *
     * @var array
     */
    $config_vars = [
        ['permissions', 'my_var', 'excluded_groups' => [-1]],
    ];

### CODE REVIEW

**Comment by emanuele45** [comment]
Why not parse the config before and pass it to the parameter?
```
		// If we have inline permissions we need to prep them.
		if (!empty($inlinePermissions) && allowedTo('manage_permissions'))
		{
			// We'll need to initialize inline permissions sub-form
			require_once(SUBSDIR . '/Permission.subs.php');
			$permissions_excluded = isset($context['permissions_excluded']) ? $context['permissions_excluded'] : array()
			if (isset($config_var['excluded_groups']))
			{
				$permissions_excluded = array_merge($permissions_excluded, $config_var['excluded_groups']);
			}
			InlinePermissions_Form::init_inline_permissions($inlinePermissions, isset($context['permissions_excluded']) ? $context['permissions_excluded'] : array());
		}
```

**Comment by live627** [comment]
That makes it more rigid. The goal here is to have different exclusions per permission.

**Comment by emanuele45** [comment]
Sorry, the code above was wrong, now it's fixed.

Yes, I think I got it, but I'm not entirely sure, so let me try to understand. ;D
You want to be able to specify for each single setting if a group can have the permission or not.
I was just thinking of re-using the already existing $excluded_groups parameters by merging for each config the $context with the parameter specified in the config array:
```
            $permissions_excluded = isset($context['permissions_excluded']) ? $context['permissions_excluded'] : array()
            if (isset($config_var['excluded_groups']))
            {
                $permissions_excluded = array_merge($permissions_excluded, $config_var['excluded_groups']);
            }
            InlinePermissions_Form::init_inline_permissions($inlinePermissions, $permissions_excluded);
________________________________________________________________________________^^^^^^^^^^^^^^^^^^^^^
// This was broken in the above code
        }
```
$permissions_excluded is specific for that particular $config.

Let's try an example.
My version:
```
$context['permissions_excluded'] = array(-1, 0);

$config_vars = [
    ['permissions', 'my_var', 'excluded_groups' => [2]],
];

$permissions_excluded = array(-1, 0, 2);
init_inline_permissions($permissions, $permissions_excluded)
```
and the three groups will not be there.

Your version:
```
$context['permissions_excluded'] = array(-1, 0);
init_inline_permissions($permissions, $context['permissions_excluded'])

$config_vars = [
    ['permissions', 'my_var', 'excluded_groups' => [2]],
];

----------------
foreach ($permissions as $permission)
{
	foreach ($excluded_groups as $group)
	{
		...
	}
	foreach ($permission['excluded_groups'] as $group)
	{
		...
	}
}
```
and the net result is the three groups will not be shown.

Of course I may have missed something, so apologize for being a pain. ;)

**Comment by live627** [comment]
Your comment left me confused. :/

The idea here is to have unique exclusions per permission.

	$config_vars = [
		['permissions', 'my_var', 'excluded_groups' => [2]],
		['permissions', 'my_var2', 'excluded_groups' => [0, 2]],
	];

Forget `$permissions_excluded` since that excludes groups across all permissions.

**Comment by emanuele45** [comment]
/me is a master of confusion. :stuck_out_tongue: 

Give me a day or so, I'm putting together a test that will work as an example. ;)

**Comment by live627** [comment]
kek

**Comment by emanuele45** [comment]
Since the stuff I put together doesn't make things easier to understand (it's just a bit of reorganization), I wrote three gists that may make things less foggy.

The current version of the code:
https://gist.github.com/emanuele45/e66fcd6724975a118c59317b59271aa4

What I think I understood your code does:
https://gist.github.com/emanuele45/c54fdaacb21a8d2529c8c734fceb085e

And finally what I was suggesting:
https://gist.github.com/emanuele45/6915fe4403f49952b8c6d03f1667aec1

Does it make more sense?

**Comment by live627** [comment]
The current code and what you are suggesting  net the same result: all permissions have the same exclusion rules. 

I'll build a test case. I actually haven't tested your code, even though I'm pretty sure it doesn't do what I'm after...

**Comment by live627** [comment]
Dummy input:

    $config_vars = [
        ['permissions', 'my_var'],
        ['permissions', 'my_var_2', 'excluded_groups' => [-1, 0]],
        ['permissions', 'my_var_3'],
        ['permissions', 'my_var_4', 'excluded_groups' => [-1]],
        ['permissions', 'my_var_5'],
    ];
    
Output of my code:

```my_var
array (
  -1 => 
  array (
    'id' => -1,
    'name' => 'Guests',
    'is_postgroup' => false,
    'status' => 'off',
  ),
  0 => 
  array (
    'id' => 0,
    'name' => 'Regular Members',
    'is_postgroup' => false,
    'status' => 'off',
  ),
  2 => 
  array (
    'id' => '2',
    'name' => 'Global Moderator',
    'is_postgroup' => false,
    'status' => 'off',
  ),
)

my_var_2
array (
  2 => 
  array (
    'id' => '2',
    'name' => 'Global Moderator',
    'is_postgroup' => false,
    'status' => 'off',
  ),
)

my_var_3
array (
  -1 => 
  array (
    'id' => -1,
    'name' => 'Guests',
    'is_postgroup' => false,
    'status' => 'off',
  ),
  0 => 
  array (
    'id' => 0,
    'name' => 'Regular Members',
    'is_postgroup' => false,
    'status' => 'off',
  ),
  2 => 
  array (
    'id' => '2',
    'name' => 'Global Moderator',
    'is_postgroup' => false,
    'status' => 'off',
  ),
)

my_var_4
array (
  0 => 
  array (
    'id' => 0,
    'name' => 'Regular Members',
    'is_postgroup' => false,
    'status' => 'off',
  ),
  2 => 
  array (
    'id' => '2',
    'name' => 'Global Moderator',
    'is_postgroup' => false,
    'status' => 'off',
  ),
)

my_var_5
array (
  -1 => 
  array (
    'id' => -1,
    'name' => 'Guests',
    'is_postgroup' => false,
    'status' => 'off',
  ),
  0 => 
  array (
    'id' => 0,
    'name' => 'Regular Members',
    'is_postgroup' => false,
    'status' => 'off',
  ),
  2 => 
  array (
    'id' => '2',
    'name' => 'Global Moderator',
    'is_postgroup' => false,
    'status' => 'off',
  ),
)```

Your code:

```my_var
array (
  2 => 
  array (
    'id' => '2',
    'name' => 'Global Moderator',
    'is_postgroup' => false,
    'status' => 'off',
  ),
)

my_var_2
array (
  2 => 
  array (
    'id' => '2',
    'name' => 'Global Moderator',
    'is_postgroup' => false,
    'status' => 'off',
  ),
)

my_var_3
array (
  2 => 
  array (
    'id' => '2',
    'name' => 'Global Moderator',
    'is_postgroup' => false,
    'status' => 'off',
  ),
)

my_var_4
array (
  2 => 
  array (
    'id' => '2',
    'name' => 'Global Moderator',
    'is_postgroup' => false,
    'status' => 'off',
  ),
)

my_var_5
array (
  2 => 
  array (
    'id' => '2',
    'name' => 'Global Moderator',
    'is_postgroup' => false,
    'status' => 'off',
  ),
)```

How I implemented it: https://github.com/elkarte/Elkarte/compare/development...live627:patch-1#diff-3171122967dd591af9349fb5fe92777bL210

**Comment by emanuele45** [comment]
I guess I was drunk before... or maybe not enough. xD

**Pull request merged**
