### PR TITLE
Fixlets

### PR DESCRIPTION
**Pull request by emanuele45**
Just a couple of minor fixes... for the first time in their own branch! xD

### CODE REVIEW

**Comment by Spuds** [comment]
I'll merge it before you can add more to this branch :smile:

**Comment by emanuele45** [comment]
Spuds wrote on 16/09/15 00:32:
>
> I'll merge it before you can add more to this branch :smile:
>
>

Nooo!! LOL

**Comment by wintstar** [comment]
:blush:  I would there still something => https://github.com/elkarte/Elkarte/issues/2227
I think that's a little something

**Comment by emanuele45** [comment]
Don't worry, I read the new bugs notifications, no need to report new bugs in PRs as well. :wink:

**Pull request merged**
