### PR TITLE
Reorganized methods to load languages and essential theme data

### PR DESCRIPTION
**Pull request by emanuele45**
Okay, the commit is a bit crazy, though... it's actually a monolith, there is no point in splitting it. :man_shrugging:

### CODE REVIEW

**Comment by emanuele45** [comment]
Forgot to mention: the side effect of this is to actually fix the display of generic icons for attachments that are not images, before that loadEssentialThemeData was failing because the theme was not loaded (since technically the download of attachments does not need the template (partially wrong, because in case of these placeholder images we actually need to know the paths), see needTheme in Attachment controller) and it was not possible to locate the file.

**Review by Spuds — APPROVED** [review]
It looks good to me ... I think splitting that out is the right thing to do.  Did not see any problems although that search replace left us with one use statements to add back as some point 😄 but there are automated tools for that.

**Comment by Spuds** [comment]
I like it 👍

**Comment by emanuele45** [comment]
> although that search replace left us with one use statements to add back as some point smile but there are automated tools for that.

I am lazy, you know. :laughing:

**Pull request merged**
