### PR TITLE
svg the message index

### PR DESCRIPTION
**Pull request by Spuds**
This is part of #2375

This uses the SVG icons for the standard sprites topic icons used on the message index.  It does not change them elsewhere as they are part of menu picks or select pulldowns.  So a minor inconsistent between the message index and the message display.   

This changes the following for the message index: poll, clip, question, exclamation, last post, lamp, thumbsup, thumbsdown, lock, sticky, sort down/up ... basically most (not all) icons that were used from the topics/topicicons.png on the message index.  See the pic

download

### CODE REVIEW

**Comment by Spuds** [comment]
I should really see if the rest of the topic icons in that sprite can be updated, I think there are only a couple left.  Then all the topic_icon class definitions could be removed from the css.   

This does keep the same css class names in the template, those could be changed to the common icon i-
 class name but was not sure if that would break custom themes.  :/

**Comment by emanuele45** [comment]
I'm pretty sure we already broke quite a bit of themes anyway. lol

**Comment by Spuds** [comment]
I'd do some more breaking then 😇

**Comment by Spuds** [comment]
Think I now converted all of the topic_icons.png file to use the existing svg images (well i did have to add a couple).

custom_variant.css was loading before the variant.css preventing variant specific overwriting.

Moved the SVG css that was in the variant files to its own file and added the ability to have a variant version to allow overwriting.  This cuts down on the redundant css, but really it was more to allow a single file edit vs two files which was easy to forget.  Added a new function to load the svg, and custom css files etc.

**Comment by Spuds** [comment]
No need to check for the file existence since loadCSSFile will do that for us.

custom.css would fallback to the the default theme ... I changed that since I think that file should be theme dependent and not falllback to any existing one in default or should it ??? Thoughts about that?

**Comment by emanuele45** [comment]
Spuds wrote on 14/07/17 13:45:
>
> No need to check for the file existence since loadCSSFile will do that
> for us.
>
> custom.css would fallback to the the default theme ... I changed that
> since I think that file should be theme dependent and not falllback to
> any existing one in default or should it ??? Thoughts about that?
>

/me agrees

**Pull request merged**
