### PR TITLE
Postgres and PHP 8.1 Fixes 

### PR DESCRIPTION
**Pull request by tinoest**
Updates for Postgres and other associated PHP 8.1 changes

### CODE REVIEW

**Comment by Spuds** [comment]
Looks like the test failures are due to the 2.0 namespacing ... some of those files will need a ```use ElkArte\Util;``` added to the top

**Comment by tinoest** [comment]
Ok, I’ll sort them tomorrow.

**Comment by tinoest** [comment]
I’m not quite sure what it’s failing on now?

Think I’ve caught all the missing namespace issues.

**Comment by Spuds** [comment]
Its a false fail, you are all clear.  I'm still working on stabilizing a couple of fetch web data test (with post data)

**Pull request merged**
