### PR TITLE
Fix avatar resizing for guests browsing the forums.

### PR DESCRIPTION
**Pull request by kode54**
Add .avatarresize style bit for guests browsing the forums.

### CODE REVIEW

**Comment by emanuele45** [comment]
I'm a bit surprised of this (unless it's a bug in 1.1 that I can't test right now), on elkarte.net it seems to work fine and the relevant code is added to the template both for logged in members and guests (i.e. browsing the forum as a guest).

Can you give me some instructions on how to reproduce the problem?

**Comment by kode54** [comment]
It needs for avatar size limits to be enforced only as CSS resizing, not re-encoding or outright disallowing.

**Comment by emanuele45** [comment]
So, I have the forum (1.1) set to "let CSS resize them (avatar)":
screen_430

and I'm browsing as a guest:
screen_430
but here I see the "resize" code block for the resize (see the bluish area of the Chrome inspect on the right).

**Comment by kode54** [comment]
It must only affect 1.0.6, then. Close and drop.

**Comment by kode54** [comment]
It also depends on user avatars on the server being noticeably larger than 65x65, the default size.

**Comment by emanuele45** [comment]
Let's keep it open to be tracked as a possible bug, it may be in a certain combination it may fail.

**Comment by emanuele45** [comment]
This was a very valid report, sorry @kode54 for dismissing it too quickly.
I pushed here another fix:
https://github.com/elkarte/Elkarte/pull/2458/commits/2210a08ecd96325710895f499e2ade30f178bb1e
I moved entirely the original code up in the chain to loadTheme where it better belongs.

**Pull request closed without merging**
