### PR TITLE
More moving color css to _light and non-color css, part II

### PR DESCRIPTION
**Pull request by Vekseid**
Got about 25-30% done, at least for these two files.

### CODE REVIEW

**Comment by Vekseid** [comment]
Is there anything wrong with this?

**Comment by Spuds** [comment]
I don't think so ... when you said 25-30% done I took it to mean don't do anything with it just yet :innocent:

**Comment by Vekseid** [comment]
Ah no. I've been trying to get others to help out with this so have been doing it in chunks.

Not a whole lot of luck on that end though >_>

**Comment by Spuds** [comment]
> Not a whole lot of luck on that end though >_>

LOL trying getting help on writing docblocks :runner: :smile_cat:

**Pull request merged**
