### PR TITLE
Db stuff

### PR DESCRIPTION
**Pull request by emanuele45**
I was in a mood of moving stuff around and so I played a bit.
Sending the PR mainly to see if it passes the tests (I can't see them executed on my repo... :man_shrugging: ) but if deemed worth it can be merged.

### CODE REVIEW

**Comment by Spuds** [comment]
MaxPain (like travis) occasionally barfs on the curl fetch to google, so I'll change that to another endpoint.  Likely getting the bot challenge or other.  The other error on 7.4/11.10 postgre may be legit.

**Comment by Spuds** [comment]
Oh to run it on your repo, you will need to change the .github/workflow/tests.yml file ... just change the repo names elkarte/elkarte to yours, and also add in your branches to monitor pull push (not sure if wildcards will work there).  Then probably add that file to the git ignore list.

**Comment by emanuele45** [comment]
Spuds wrote on 2/2/21 12:53 AM:
>
> MaxPain (like travis) occasionally barfs on the curl fetch to google, 
> so I'll change that to another endpoint.
>

Yep, noticed that. Since it is just a GET, maybe github could be used... 
:shrugs:

> Likely getting the bot challenge or other. The other error on 
> 7.4/11.10 postgre may be legit.
>

True... I'm not sure what the problem it, though... I'll try to fix. xD

**Comment by Spuds** [comment]
I'll take a look in just a bit ... I've been updating things to use phpunit 8 so we are no so far behind and there were a lot of depreciations and small changes to help Maximize da pain!   V8 is still supported for like 3 more weeks and also has a min requirement of 7.2 so no more 7.1 tests.

**Comment by Spuds** [comment]
@emanuele45 I just noticed we are getting a ```BLOB/TEXT column 'notification_type' used in key specification without a key length```  notification_type is being used as a key so mysql (at least) wants an index length on that text key ... maybe varchar instead that support 65K I thought, but maybe not with postgre

**Comment by Spuds** [comment]
@emanuele45 The two search errors were due to me forgetting to change the testcase from stuffing ```$_GET['search']``` to ```$req->query['search']```  Some other errors (web and look at mysql) are due to the above mentioned TEXT/BLOB being used in the key which causes MySQL/MariaDB failing on instalation of the DB

Still looking into the PBE thing

**Comment by Spuds** [comment]
I see that ```1) TestDatabase::testTablesPopulated
The number of inserted rows for the table settings doesn't match the expectations (202 -VS- 204)
Failed asserting that 204 matches expected '202'.``
So lets start with getting that DB (and MySql/mariaDB) to install proper before much else.   As a temp work around changing the notification type in install from type ```text``` to ```varchar with size 512``` appears to work for the install and the index

**Comment by Spuds** [comment]
@emanuele45 so playing around with the ```notifications_pref``` table and I learned something.  

I kept getting the data to long for column error with text or varchar(512) when inserting the data which was certainly short enough to fit.  Then I thought maybe it was because it was JSON data and some encoding problem, so changed the column type to JSON and that seemed to work.  However different levels of MySQL and Postgre had issues with using a JSON column in the index. 

Then it dawned on me, 🤦 that stupid error of ```data to long for column``` was about the index not the actual field!  So changing ```notification_type``` back to text or perhaps better varchar 256 and then using ```notification_type(64)``` when creating the index works.  That will use the first 64 characters of the field in the index.  I don't think that field will be longer than 64, and if shorter we could lower that.

**Comment by emanuele45** [comment]
Spuds wrote on 2/3/21 2:31 AM:
>
> I see that |1) TestDatabase::testTablesPopulated The number of 
> inserted rows for the table settings doesn't match the expectations 
> (202 -VS- 204) Failed asserting that 204 matches expected '202'.`` So 
> lets start with getting that DB (and MySql/mariaDB) to install proper 
> before much else. As a temp work around changing the notification type 
> in install from type |text|to|varchar with size 512``` appears to work 
> for the install and the index
>

I *feel* most of these errors are due to the replace method I introduced 
in this branch and the roundabout way to impleent the behaviour. Since 
we are using PSQL 9.5 for testing I assume this is also our lower 
target, so I tried using ON CONFLICT and locally seems to work. On top 
of that, the transactions were not working as expected and this was 
another issue.
Let's see with my latest commit... :fingers_crossed: ! xD

**Comment by emanuele45** [comment]
Oh well... *technically* it passed. :laughing: 
Is it necessary to go and open the test to see that it did not even connect to the server? :angel:

**Comment by Spuds** [comment]
The reason for the duplicate index is the mention test was not updated to use the json array.   https://github.com/Spuds/Elkarte/commit/3f0c957bb579ea00647fde48ef35681137085f5b

I originally thought the notification key was not needed as well, but then that error appeared but its due to the test.  So drop that key (or use the length trick), update the test, have a beer

**Comment by Spuds** [comment]
I'm not sure why the db install step showed passed when in fact it failed to connect as it failed to even install due to the index key length issue.  postgre just skipped the bad tables an mysql simply died. 

Its something to look into to.  It also was the reason the web tests failed, since installing the db failed during that testing, I was to hasty to ignore that as a selenium issue but it was because the db install was failing.

**Comment by Spuds** [comment]
On a positive note, with the mentions and search tests fixed (and a bunch of other busy work), my php unit 8 now passes on the dev branch 😄 https://github.com/Spuds/Elkarte/actions/runs/534623410

**Comment by Spuds** [comment]
@emanuele45 Just in case you were hopeful, postgre did not pass, no connection to the db
```
PostgreSQL server version: 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1)
ERROR:  column "id_group" does not exist
LINE 7:    ('read_only')ON CONFLICT (id_group) DO NOTHING
+ sudo rm -rf /install
```

**Comment by Spuds** [comment]
In my pending test update PR I've added the db install fail detection so in the future those errors should be caught

**Comment by emanuele45** [comment]
Spuds wrote on 2/3/21 9:31 PM:
>
> @emanuele45 Just in case you were hopeful, postgre did not pass, no connection to the db
> PostgreSQL server version: 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1)
> ERROR:  column "id_group" does not exist
> LINE 7:    ('read_only')ON CONFLICT (id_group) DO NOTHING
> \+ sudo rm -rf /install

You broke the magic. :laughing:

**Comment by Spuds** [comment]
My prediction for PR's not passing tests .... Pain, Maximum Pain!  Mr. T-bot

So is this good to go now?   I want to PR in the updated tests with phpunit 8 and other fixes

**Comment by emanuele45** [comment]
Spuds wrote on 2/3/21 10:48 PM:
>
> In my pending test update PR I've added the db install fail detection 
> so in the future those errors should be caught
>
Cool!

> My prediction for PR's not passing tests .... Pain, Maximum Pain! Mr. 
> T-bot
>
> So is this good to go now? I want to PR in the updated tests with 
> phpunit 8 and other fixes
>

Aaaand that one seems all green now! :D
So, up to you!

**Comment by Spuds** [comment]
This has some nice changes!

**Pull request merged**
