### PR TITLE
Update to 1 1 6

### PR DESCRIPTION
**Pull request by emanuele45**

### CODE REVIEW

**Comment by emanuele45** [comment]
As usual, @Spuds give a quick review, this kind of merges are always rather tricky...

**Comment by Spuds** [comment]
"tricky" is the nicest description I can think of ... most of the Travis errors came from curl fetch web so those are somewhat bogus .... There was one other that I have not looked at.

**Comment by emanuele45** [comment]
Well, if it is just the post I'd be happy. :joy:
I meant more in general due to the number of conflicts that are easy to overlook... :-\

**Comment by Spuds** [comment]
I'm going to pull this in, we can deal with the aftermath then 😇

**Pull request merged**
