### PR TITLE
Some low-hanging icon fruit

### PR DESCRIPTION
**Pull request by Vekseid**
Stuff that was simple enough to get out of the way for beta 1. : )

### CODE REVIEW

**Comment by emanuele45** [comment]
Maybe just dump everything in the template? (And keep the index definition there just to avoid undefined indexes around.)

Oh, and that reminds me that the sorting template could very well be split out in a dedicated template function. :angel:

**Comment by Vekseid** [comment]
Yeah there are a number of functions like that. Some things I am treading on comparatively lightly at the moment because I've got ideas for how to generify them.

**Comment by Vekseid** [comment]
Going to try to get a few more icons in.

**Comment by emanuele45** [comment]
> Yeah there are a number of functions like that. Some things I am treading on comparatively lightly at the moment because I've got ideas for how to generify them.

Probably the best would actually be to completely unify the two templates... well, at least some.

**Comment by Vekseid** [comment]
The best would be a full refactoring. That's a post-1.1 discussion though I think.

**Comment by Vekseid** [comment]
So many things are... creatively embedded into the code. : /

**Pull request merged**
