### PR TITLE
Fix and test internal admin search

### PR DESCRIPTION
**Pull request by live627**
Some labels weren't resolved

### CODE REVIEW

**Comment by live627** [comment]
Huh... the tests are running but no coverage increase? Wha?

**Comment by Spuds** [comment]
Some coverage when down ... 

I think since the coverage test (which is the php 5.6 run) did have some errors (selenium again), perhaps that caused the coverage report to miss a few items.   

I restarted it and it ran fine.  It may be that the selenium tests need a short delay added to the browser and head to give it a chance to respond before items are checked?

**Comment by emanuele45** [comment]
I forgot about this one... can be merged?

**Comment by live627** [comment]
ofc

**Comment by live627** [comment]
@emanuele45 you up late xD

**Pull request merged**
