### PR TITLE
Censor

### PR DESCRIPTION
**Pull request by joshuaadickerson**
I think the censor should be its own class. Really, though, the reason I finally went ahead and committed this is so I could change `$user_profile` from `Array[]` to `ValuesContainer[]` and later `User[]`

You'll see a PR for this later...

From
```php
		$new_loaded_ids = array();
		while ($row = $db->fetch_assoc($request))
		{
			$new_loaded_ids[] = $row['id_member'];
			$loaded_ids[] = $row['id_member'];
			$row['options'] = array();
			$user_profile[$row['id_member']] = $row;
		}
		$db->free_result($request);
```
To
```php
		require_once(SOURCEDIR . '/ValuesContainer.php');
		$new_loaded_ids = array();
		while ($row = $db->fetch_assoc($request))
		{
			$new_loaded_ids[] = $row['id_member'];
			$loaded_ids[] = $row['id_member'];
			$row['options'] = array();
			$user_profile[$row['id_member']] = new \ElkArte\ValuesContainer($row);
		}
		$db->free_result($request);

### CODE REVIEW

**Comment by emanuele45** [comment]
Ouch I used the wrong file name! (forgot the .class)
Anyway, the "require_once" should not be necessary. :P

**Comment by joshuaadickerson** [comment]
It doesn't work without the cache

**Comment by joshuaadickerson** [comment]
"class"

On my phone

**Comment by joshuaadickerson** [comment]
If ".class" isn't there, it doesn't work without including the file.

**Comment by emanuele45** [comment]
Odd, I used it in few places, but never require'd the file... :confused: 
Ohh well, who cares.

**Pull request merged**
